### ISSUE TITLE
🐛 [firebase_ui_firestore] Scroll position jumps to start when calling setState()

### ISSUE THREAD

**Issue by rorystephenson** [firebase/FirebaseUI-Flutter#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Firestore

### What platform(s) does this bug affect?

Android, iOS, Web, macOS, Linux, Windows

### List of dependencies used.

<details>
<summary>flutter pub deps -s list | grep firestore</summary>
<pre>
- cloud_firestore 4.9.2
  - cloud_firestore_platform_interface ^5.16.1
  - cloud_firestore_web ^3.7.1
- firestore_ui 1.25.1
  - cloud_firestore ^4.3.1
  - cloud_firestore_platform_interface ^5.10.1
- firebase_ui_firestore 1.5.11
  - cloud_firestore ^4.9.1
- cloud_firestore_platform_interface 5.16.1
- cloud_firestore_web 3.7.1
  - cloud_firestore_platform_interface ^5.16.1
</pre>
</details>

### Steps to reproduce

Place FirestoreListView in a stateful widget, scroll down and trigger a setState (e.g. with a button).

### Expected Behavior

Scroll offset is maintained

### Actual Behavior

Scroll position is reset back to the start.

### Additional Information

The scroll position also resets to the start every time the snapshot for the query I am listening to updates.

**Comment by danagbemava-nc** [comment]
Hi @rorystephenson, I used the plugin example, and after triggering a setState, the offset didn't change. Can you share a minimal complete reproducible code sample in a repo that we can clone so that we can investigate this?

**Comment by rorystephenson** [comment]
I've had a go with your example app and you're 100% right. I've deleted the code I was playing with but I'm pretty sure that the reason for the scroll re-setting, and I can reproduce it in the app, is that rather than providing a fixed instance of my collection reference as the `query` parameter it was coming from a getter.

To see what I mean try changing the `query` parameter in the example app from the `collection` variable to:
```dart
query: FirebaseFirestore.instance
    .collection('users')
    .withConverter<User>(
      fromFirestore: (snapshot, _) =>
          User.fromJson(snapshot.data()!),
      toFirestore: (user, _) => user.toJson(),
    ),
```

Then setState() will cause the list to scroll back to the top.

I'm not sure if there's a way to compare the old and new `query` values and see if they are equivalent rather than relying on them being the same instance or whether you want to do that but in any case this is resolved 👍 .

**Comment by sdattatri** [comment]
Hi, I am having the same issue. I have a FireStoreListView and when I call setState elsewhere the FireStoreListView gets refreshed and scrolls back to the top. I have tried using a ScrollController but is seems to have no effect at all.
