### ISSUE TITLE
🐛 Login with email with incorrect credentials throw an exception.

### ISSUE THREAD

**Issue by JobiJoba** [firebase/FirebaseUI-Flutter#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Auth

### What platform(s) does this bug affect?

iOS

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
Dart SDK 3.1.0
Flutter SDK 3.13.1

dependencies:
- camera 0.10.5+5
  - camera_android ^0.10.7
  - camera_avfoundation ^0.9.13
  - camera_platform_interface ^2.5.0
  - camera_web ^0.3.1
  - flutter any
  - flutter_plugin_android_lifecycle ^2.0.2
  - quiver ^3.0.0
- cloud_firestore 4.9.3
  - cloud_firestore_platform_interface ^5.16.2
  - cloud_firestore_web ^3.7.2
  - collection ^1.0.0
  - firebase_core ^2.17.0
  - firebase_core_platform_interface ^4.8.0
  - flutter any
  - meta ^1.8.0
- device_info_plus 9.0.3
  - device_info_plus_platform_interface ^7.0.0
  - ffi ^2.0.1
  - file >=6.1.4 <8.0.0
  - flutter any
  - flutter_web_plugins any
  - meta ^1.8.0
  - win32 >=4.0.0 <6.0.0
  - win32_registry ^1.1.0
- firebase_analytics 10.5.1
  - firebase_analytics_platform_interface ^3.7.1
  - firebase_analytics_web ^0.5.5+1
  - firebase_core ^2.17.0
  - firebase_core_platform_interface ^4.8.0
  - flutter any
- firebase_auth 4.10.1
  - firebase_auth_platform_interface ^6.19.1
  - firebase_auth_web ^5.8.2
  - firebase_core ^2.17.0
  - firebase_core_platform_interface ^4.8.0
  - flutter any
  - meta ^1.8.0
- firebase_core 2.17.0
  - firebase_core_platform_interface ^4.8.0
  - firebase_core_web ^2.8.0
  - flutter any
  - meta ^1.8.0
- firebase_crashlytics 3.3.7
  - firebase_core ^2.17.0
  - firebase_core_platform_interface ^4.8.0
  - firebase_crashlytics_platform_interface ^3.6.7
  - flutter any
  - stack_trace ^1.10.0
- firebase_messaging 14.6.9
  - firebase_core ^2.17.0
  - firebase_core_platform_interface ^4.8.0
  - firebase_messaging_platform_interface ^4.5.8
  - firebase_messaging_web ^3.5.8
  - flutter any
  - meta ^1.8.0
- firebase_ui_auth 1.8.0
  - email_validator ^2.1.17
  - firebase_auth ^4.9.0
  - firebase_core ^2.15.1
  - firebase_dynamic_links ^5.3.4
  - firebase_ui_localizations ^1.6.1
  - firebase_ui_oauth ^1.4.11
  - firebase_ui_shared ^1.3.1
  - flutter any
  - flutter_localizations any
- firebase_ui_oauth_apple 1.2.11
  - firebase_auth ^4.9.0
  - firebase_ui_oauth ^1.4.11
  - flutter any
- firebase_ui_oauth_google 1.2.11
  - firebase_auth ^4.9.0
  - firebase_ui_oauth ^1.4.11
  - flutter any
  - google_sign_in ^6.1.0
- flutter 0.0.0
  - characters 1.3.0
  - collection 1.17.2
  - material_color_utilities 0.5.0
  - meta 1.9.1
  - vector_math 2.1.4
  - web 0.1.4-beta
  - sky_engine any
- flutter_hooks 0.20.2
  - flutter any
- flutter_native_splash 2.3.3
  - args ^2.4.2
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.7
  - html ^0.15.4
  - image ^4.1.3
  - meta ^1.9.1
  - path ^1.8.3
  - universal_io ^2.2.2
  - xml ^6.3.0
  - yaml ^3.1.2
- flutter_svg 2.0.7
  - flutter any
  - vector_graphics ^1.1.7
  - vector_graphics_codec ^1.1.7
  - vector_graphics_compiler ^1.1.7
- flutter_vision 1.1.3
  - flutter any
  - path ^1.8.1
  - path_provider ^2.0.11
- geolocator 10.1.0
  - flutter any
  - geolocator_platform_interface ^4.1.0
  - geolocator_android ^4.3.0
  - geolocator_apple ^2.3.0
  - geolocator_web ^2.2.0
  - geolocator_windows ^0.2.1
- go_router 11.1.2
  - collection ^1.15.0
  - flutter any
  - flutter_web_plugins any
  - logging ^1.0.0
  - meta ^1.7.0
- google_sign_in 6.1.5
  - flutter any
  - google_sign_in_android ^6.1.0
  - google_sign_in_ios ^5.5.0
  - google_sign_in_platform_interface ^2.4.0
  - google_sign_in_web ^0.12.0
- hooks_riverpod 2.4.2
  - collection ^1.15.0
  - flutter any
  - flutter_hooks >=0.18.0 <0.21.0
  - flutter_riverpod 2.4.2
  - riverpod 2.4.1
  - state_notifier >=0.7.2 <2.0.0
- introduction_screen 3.1.12
  - flutter any
  - collection ^1.17.1
  - dots_indicator ^2.1.2
  - flutter_keyboard_visibility ^5.4.1
- kdtree 0.2.0
- lottie 2.6.0
  - archive ^3.0.0
  - flutter any
  - path ^1.8.0
  - vector_math ^2.1.0
- permission_handler 11.0.0
  - flutter any
  - meta ^1.7.0
  - permission_handler_android ^11.0.0
  - permission_handler_apple ^9.1.4
  - permission_handler_windows ^0.1.3
  - permission_handler_platform_interface ^3.11.5
- riverpod_annotation 2.1.6
  - meta ^1.7.0
  - riverpod ^2.4.1
- shared_preferences 2.2.1
  - flutter any
  - shared_preferences_android ^2.1.0
  - shared_preferences_foundation ^2.2.0
  - shared_preferences_linux ^2.2.0
  - shared_preferences_platform_interface ^2.3.0
  - shared_preferences_web ^2.1.0
  - shared_preferences_windows ^2.2.0
- uuid 3.0.7
  - crypto ^3.0.0

dev dependencies:
- build_runner 2.4.6
  - analyzer >=4.4.0 <7.0.0
  - args ^2.0.0
  - async ^2.5.0
  - build >=2.1.0 <2.5.0
  - build_config >=1.1.0 <1.2.0
  - build_daemon ^4.0.0
  - build_resolvers ^2.0.0
  - build_runner_core ^7.2.0
  - code_builder ^4.2.0
  - collection ^1.15.0
  - crypto ^3.0.0
  - dart_style ^2.0.0
  - frontend_server_client ^3.0.0
  - glob ^2.0.0
  - graphs ^2.2.0
  - http_multi_server ^3.0.0
  - io ^1.0.0
  - js ^0.6.3
  - logging ^1.0.0
  - meta ^1.3.0
  - mime ^1.0.0
  - package_config ^2.0.0
  - path ^1.8.0
  - pool ^1.5.0
  - pub_semver ^2.0.0
  - pubspec_parse ^1.0.0
  - shelf ^1.0.0
  - shelf_web_socket ^1.0.0
  - stack_trace ^1.10.0
  - stream_transform ^2.0.0
  - timing ^1.0.0
  - watcher ^1.0.0
  - web_socket_channel ^2.0.0
  - yaml ^3.0.0
- custom_lint 0.5.3
  - analyzer >=5.12.0 <7.0.0
  - analyzer_plugin ^0.11.0
  - args ^2.3.1
  - async ^2.9.0
  - ci ^0.1.0
  - cli_util ^0.4.0
  - collection ^1.16.0
  - freezed_annotation ^2.2.0
  - json_annotation ^4.7.0
  - meta ^1.7.0
  - package_config ^2.0.2
  - path ^1.8.0
  - pub_semver ^2.1.1
  - pubspec_parse ^1.2.0
  - rxdart ^0.27.7
  - uuid ^3.0.6
  - yaml ^3.1.1
- flutter_launcher_icons 0.13.1
  - args ^2.3.2
  - checked_yaml ^2.0.2
  - cli_util ^0.4.0
  - image ^4.0.15
  - json_annotation ^4.8.0
  - path ^1.8.2
  - yaml ^3.1.1
- riverpod_generator 3.0.0-dev.2
  - analyzer >=6.0.0 <7.0.0
  - build ^2.0.0
  - build_config ^1.0.0
  - collection ^1.15.0
  - crypto ^3.0.2
  - meta ^1.7.0
  - path ^1.8.0
  - riverpod_analyzer_utils ^0.4.0
  - riverpod_annotation ^2.1.6
  - source_gen ^1.2.0
- riverpod_lint 2.2.1
  - analyzer >=6.0.0 <7.0.0
  - analyzer_plugin ^0.11.2
  - collection ^1.16.0
  - custom_lint_builder ^0.5.2
  - meta ^1.7.0
  - path ^1.8.1
  - riverpod ^2.4.1
  - riverpod_analyzer_utils ^0.4.0
  - source_span ^1.8.0
  - yaml ^3.1.1
- very_good_analysis 5.1.0

transitive dependencies:
- _fe_analyzer_shared 64.0.0
  - meta ^1.9.0
- _flutterfire_internals 1.3.7
  - collection ^1.0.0
  - firebase_core ^2.17.0
  - firebase_core_platform_interface ^4.8.0
  - flutter any
  - meta ^1.8.0
- analyzer 6.2.0
  - _fe_analyzer_shared ^64.0.0
  - collection ^1.17.0
  - convert ^3.0.0
  - crypto ^3.0.0
  - glob ^2.0.0
  - meta ^1.7.0
  - package_config ^2.0.0
  - path ^1.8.0
  - pub_semver ^2.0.0
  - source_span ^1.8.0
  - watcher ^1.0.0
  - yaml ^3.0.0
- analyzer_plugin 0.11.3
  - analyzer ^6.0.0
  - collection ^1.15.0
  - dart_style ^2.2.1
  - pub_semver ^2.1.0
  - yaml ^3.1.0
- archive 3.4.4
  - crypto ^3.0.3
  - path ^1.8.0
  - pointycastle ^3.6.2
- args 2.4.2
- async 2.11.0
  - collection ^1.15.0
  - meta ^1.1.7
- boolean_selector 2.1.1
  - source_span ^1.8.0
  - string_scanner ^1.1.0
- build 2.4.1
  - analyzer >=1.5.0 <7.0.0
  - async ^2.5.0
  - convert ^3.0.0
  - crypto ^3.0.0
  - glob ^2.0.0
  - logging ^1.0.0
  - meta ^1.3.0
  - package_config ^2.1.0
  - path ^1.8.0
- build_config 1.1.1
  - checked_yaml ^2.0.0
  - json_annotation ^4.5.0
  - path ^1.8.0
  - pubspec_parse ^1.0.0
  - yaml ^3.0.0
- build_daemon 4.0.0
  - built_collection ^5.0.0
  - built_value ^8.1.0
  - http_multi_server ^3.0.0
  - logging ^1.0.0
  - path ^1.8.0
  - pool ^1.5.0
  - shelf ^1.0.0
  - shelf_web_socket ^1.0.0
  - stream_transform ^2.0.0
  - watcher ^1.0.0
  - web_socket_channel ^2.0.0
- build_resolvers 2.4.1
  - analyzer >=5.12.0 <7.0.0
  - async ^2.5.0
  - build ^2.0.0
  - collection ^1.17.0
  - convert ^3.1.1
  - crypto ^3.0.0
  - graphs >=1.0.0 <3.0.0
  - logging ^1.0.0
  - package_config ^2.0.0
  - path ^1.8.0
  - pool ^1.5.0
  - pub_semver ^2.0.0
  - stream_transform ^2.0.0
  - yaml ^3.0.0
- build_runner_core 7.2.11
  - async ^2.5.0
  - build ^2.4.0
  - build_config ^1.0.0
  - build_resolvers ^2.4.0
  - collection ^1.15.0
  - convert ^3.0.0
  - crypto ^3.0.0
  - glob ^2.0.0
  - graphs ^2.0.0
  - json_annotation ^4.8.1
  - logging ^1.2.0
  - meta ^1.3.0
  - package_config ^2.0.0
  - path ^1.8.0
  - pool ^1.5.0
  - timing ^1.0.0
  - watcher ^1.0.0
  - yaml ^3.0.0
- built_collection 5.1.1
- built_value 8.6.3
  - built_collection ^5.0.0
  - collection ^1.15.0
  - fixnum ^1.0.0
  - meta ^1.3.0
- camera_android 0.10.8+12
  - camera_platform_interface ^2.5.0
  - flutter any
  - flutter_plugin_android_lifecycle ^2.0.2
  - stream_transform ^2.0.0
- camera_avfoundation 0.9.13+6
  - camera_platform_interface ^2.4.0
  - flutter any
  - stream_transform ^2.0.0
- camera_platform_interface 2.5.2
  - cross_file ^0.3.1
  - flutter any
  - plugin_platform_interface ^2.1.0
  - stream_transform ^2.0.0
- camera_web 0.3.2+3
  - camera_platform_interface ^2.3.1
  - flutter any
  - flutter_web_plugins any
  - stream_transform ^2.0.0
- characters 1.3.0
- checked_yaml 2.0.3
  - json_annotation ^4.3.0
  - source_span ^1.8.0
  - yaml ^3.0.0
- ci 0.1.0
- cli_util 0.4.0
  - meta ^1.3.0
  - path ^1.8.0
- clock 1.1.1
- cloud_firestore_platform_interface 5.16.2
  - _flutterfire_internals ^1.3.7
  - collection ^1.15.0
  - firebase_core ^2.17.0
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- cloud_firestore_web 3.7.2
  - _flutterfire_internals ^1.3.7
  - cloud_firestore_platform_interface ^5.16.2
  - collection ^1.0.0
  - firebase_core ^2.17.0
  - firebase_core_web ^2.8.0
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
- code_builder 4.7.0
  - built_collection ^5.0.0
  - built_value ^8.0.0
  - collection ^1.15.0
  - matcher ^0.12.10
  - meta ^1.3.0
- collection 1.17.2
- convert 3.1.1
  - typed_data ^1.3.0
- cross_file 0.3.3+5
  - js ^0.6.3
  - meta ^1.3.0
- crypto 3.0.3
  - typed_data ^1.3.0
- csslib 1.0.0
  - source_span ^1.8.0
- custom_lint_builder 0.5.3
  - analyzer >=5.12.0 <7.0.0
  - analyzer_plugin ^0.11.0
  - collection ^1.16.0
  - custom_lint 0.5.3
  - custom_lint_core 0.5.3
  - glob ^2.1.1
  - hotreloader ^3.0.5
  - meta ^1.7.0
  - path ^1.8.0
  - pubspec_parse ^1.2.0
  - rxdart ^0.27.7
- custom_lint_core 0.5.3
  - analyzer >=5.12.0 <7.0.0
  - analyzer_plugin ^0.11.0
  - collection ^1.16.0
  - custom_lint 0.5.3
  - matcher ^0.12.0
  - meta ^1.7.0
  - path ^1.8.0
  - pubspec_parse ^1.2.2
  - source_span ^1.8.0
  - yaml ^3.1.1
- dart_style 2.3.3
  - analyzer ^6.2.0
  - args >=1.0.0 <3.0.0
  - path ^1.0.0
  - pub_semver >=1.4.4 <3.0.0
  - source_span ^1.4.0
- desktop_webview_auth 0.0.13
  - crypto ^3.0.3
  - flutter any
  - http ^1.0.0
  - flutter_web_plugins any
  - plugin_platform_interface ^2.1.4
- device_info_plus_platform_interface 7.0.0
  - flutter any
  - meta ^1.3.0
  - plugin_platform_interface ^2.0.0
- dots_indicator 2.1.2
  - flutter any
- email_validator 2.1.17
- fake_async 1.3.1
  - clock ^1.1.0
  - collection ^1.15.0
- ffi 2.1.0
- file 6.1.4
  - meta ^1.3.0
  - path ^1.8.0
- firebase_analytics_platform_interface 3.7.1
  - _flutterfire_internals ^1.3.7
  - firebase_core ^2.17.0
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_analytics_web 0.5.5+1
  - _flutterfire_internals ^1.3.7
  - firebase_analytics_platform_interface ^3.7.1
  - firebase_core ^2.17.0
  - firebase_core_web ^2.8.0
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
- firebase_auth_platform_interface 6.19.1
  - _flutterfire_internals ^1.3.7
  - collection ^1.16.0
  - firebase_core ^2.17.0
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_auth_web 5.8.2
  - firebase_auth_platform_interface ^6.19.1
  - firebase_core ^2.17.0
  - firebase_core_web ^2.8.0
  - flutter any
  - flutter_web_plugins any
  - http_parser ^4.0.0
  - js ^0.6.3
  - meta ^1.8.0
- firebase_core_platform_interface 4.8.0
  - collection ^1.0.0
  - flutter any
  - flutter_test any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_core_web 2.8.0
  - firebase_core_platform_interface ^4.8.0
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
  - meta ^1.8.0
- firebase_crashlytics_platform_interface 3.6.7
  - _flutterfire_internals ^1.3.7
  - collection ^1.15.0
  - firebase_core ^2.17.0
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_dynamic_links 5.3.7
  - firebase_core ^2.17.0
  - firebase_core_platform_interface ^4.8.0
  - firebase_dynamic_links_platform_interface ^0.2.6+7
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_dynamic_links_platform_interface 0.2.6+7
  - _flutterfire_internals ^1.3.7
  - firebase_core ^2.17.0
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_messaging_platform_interface 4.5.8
  - _flutterfire_internals ^1.3.7
  - firebase_core ^2.17.0
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_messaging_web 3.5.8
  - _flutterfire_internals ^1.3.7
  - firebase_core ^2.17.0
  - firebase_core_web ^2.8.0
  - firebase_messaging_platform_interface ^4.5.8
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
  - meta ^1.8.0
- firebase_ui_localizations 1.6.1
  - flutter any
  - flutter_localizations any
  - path ^1.8.2
- firebase_ui_oauth 1.4.11
  - desktop_webview_auth ^0.0.13
  - firebase_auth ^4.9.0
  - firebase_ui_auth ^1.8.0
  - firebase_ui_shared ^1.3.1
  - flutter_svg ^2.0.7
  - flutter any
- firebase_ui_shared 1.3.1
  - flutter any
- fixnum 1.1.0
- flutter_keyboard_visibility 5.4.1
  - meta >=1.0.0 <2.0.0
  - flutter_keyboard_visibility_platform_interface ^2.0.0
  - flutter_keyboard_visibility_linux ^1.0.0
  - flutter_keyboard_visibility_macos ^1.0.0
  - flutter_keyboard_visibility_web ^2.0.0
  - flutter_keyboard_visibility_windows ^1.0.0
  - flutter any
- flutter_keyboard_visibility_linux 1.0.0
  - flutter_keyboard_visibility_platform_interface ^2.0.0
  - flutter any
- flutter_keyboard_visibility_macos 1.0.0
  - flutter_keyboard_visibility_platform_interface ^2.0.0
  - flutter any
- flutter_keyboard_visibility_platform_interface 2.0.0
  - flutter any
  - meta >=1.0.0 <2.0.0
  - plugin_platform_interface ^2.0.0
- flutter_keyboard_visibility_web 2.0.0
  - flutter_keyboard_visibility_platform_interface ^2.0.0
  - flutter_web_plugins any
  - flutter any
- flutter_keyboard_visibility_windows 1.0.0
  - flutter_keyboard_visibility_platform_interface ^2.0.0
  - flutter any
- flutter_localizations 0.0.0
  - flutter any
  - intl 0.18.1
  - characters 1.3.0
  - clock 1.1.1
  - collection 1.17.2
  - material_color_utilities 0.5.0
  - meta 1.9.1
  - path 1.8.3
  - vector_math 2.1.4
  - web 0.1.4-beta
- flutter_plugin_android_lifecycle 2.0.16
  - flutter any
- flutter_riverpod 2.4.2
  - collection ^1.15.0
  - flutter any
  - meta ^1.4.0
  - riverpod 2.4.1
  - state_notifier >=0.7.2 <2.0.0
- flutter_test 0.0.0
  - flutter any
  - test_api 0.6.0
  - matcher 0.12.16
  - path 1.8.3
  - fake_async 1.3.1
  - clock 1.1.1
  - stack_trace 1.11.0
  - vector_math 2.1.4
  - async 2.11.0
  - boolean_selector 2.1.1
  - characters 1.3.0
  - collection 1.17.2
  - material_color_utilities 0.5.0
  - meta 1.9.1
  - source_span 1.10.0
  - stream_channel 2.1.1
  - string_scanner 1.2.0
  - term_glyph 1.2.1
  - web 0.1.4-beta
- flutter_web_plugins 0.0.0
  - flutter any
  - characters 1.3.0
  - collection 1.17.2
  - material_color_utilities 0.5.0
  - meta 1.9.1
  - vector_math 2.1.4
  - web 0.1.4-beta
- freezed_annotation 2.4.1
  - collection ^1.15.0
  - json_annotation ^4.6.0
  - meta ^1.7.0
- frontend_server_client 3.2.0
  - async ^2.5.0
  - path ^1.8.0
- geolocator_android 4.3.1
  - flutter any
  - geolocator_platform_interface ^4.1.0
  - uuid ^3.0.7
- geolocator_apple 2.3.2
  - flutter any
  - geolocator_platform_interface ^4.1.0
- geolocator_platform_interface 4.1.1
  - flutter any
  - plugin_platform_interface ^2.1.6
  - vector_math ^2.1.4
  - meta ^1.9.1
- geolocator_web 2.2.0
  - flutter any
  - flutter_web_plugins any
  - geolocator_platform_interface ^4.1.0
- geolocator_windows 0.2.1
  - flutter any
  - geolocator_platform_interface ^4.1.0
- glob 2.1.2
  - async ^2.5.0
  - collection ^1.15.0
  - file >=6.1.3 <8.0.0
  - path ^1.8.0
  - string_scanner ^1.1.0
- google_identity_services_web 0.2.1+1
  - js ^0.6.4
  - meta ^1.3.0
- google_sign_in_android 6.1.20
  - flutter any
  - google_sign_in_platform_interface ^2.2.0
- google_sign_in_ios 5.6.3
  - flutter any
  - google_sign_in_platform_interface ^2.2.0
- google_sign_in_platform_interface 2.4.2
  - flutter any
  - plugin_platform_interface ^2.1.0
  - quiver ^3.0.0
- google_sign_in_web 0.12.0+5
  - flutter any
  - flutter_web_plugins any
  - google_identity_services_web ^0.2.1
  - google_sign_in_platform_interface ^2.4.0
  - http >=0.13.0 <2.0.0
  - js ^0.6.3
- graphs 2.3.1
  - collection ^1.1.0
- hotreloader 3.0.6
  - collection ^1.15.0
  - logging ^1.0.0
  - path ^1.8.0
  - stream_transform ^2.0.0
  - vm_service >=6.0.1 <12.0.0
  - watcher ^1.0.0
- html 0.15.4
  - csslib >=0.17.0 <2.0.0
  - source_span ^1.8.0
- http 1.1.0
  - async ^2.5.0
  - http_parser ^4.0.0
  - meta ^1.3.0
- http_multi_server 3.2.1
  - async ^2.5.0
- http_parser 4.0.2
  - collection ^1.15.0
  - source_span ^1.8.0
  - string_scanner ^1.1.0
  - typed_data ^1.3.0
- image 4.1.3
  - archive ^3.4.0
  - meta ^1.3.0
  - xml ^6.0.1
- intl 0.18.1
  - clock ^1.1.0
  - meta ^1.0.2
  - path ^1.8.0
- io 1.0.4
  - meta ^1.3.0
  - path ^1.8.0
  - string_scanner ^1.1.0
- js 0.6.7
  - meta ^1.7.0
- json_annotation 4.8.1
  - meta ^1.4.0
- logging 1.2.0
- matcher 0.12.16
  - async ^2.10.0
  - meta ^1.8.0
  - stack_trace ^1.10.0
  - term_glyph ^1.2.0
  - test_api >=0.5.0 <0.7.0
- material_color_utilities 0.5.0
  - collection ^1.15.0
- meta 1.9.1
- mime 1.0.4
- package_config 2.1.0
  - path ^1.8.0
- path 1.8.3
- path_parsing 1.0.1
  - vector_math ^2.1.0
  - meta ^1.3.0
- path_provider 2.1.1
  - flutter any
  - path_provider_android ^2.1.0
  - path_provider_foundation ^2.3.0
  - path_provider_linux ^2.2.0
  - path_provider_platform_interface ^2.1.0
  - path_provider_windows ^2.2.0
- path_provider_android 2.2.0
  - flutter any
  - path_provider_platform_interface ^2.1.0
- path_provider_foundation 2.3.1
  - flutter any
  - path_provider_platform_interface ^2.1.0
- path_provider_linux 2.2.1
  - ffi >=1.1.2 <3.0.0
  - flutter any
  - path ^1.8.0
  - path_provider_platform_interface ^2.1.0
  - xdg_directories >=0.2.0 <2.0.0
- path_provider_platform_interface 2.1.1
  - flutter any
  - platform ^3.0.0
  - plugin_platform_interface ^2.1.0
- path_provider_windows 2.2.1
  - ffi ^2.0.0
  - flutter any
  - path ^1.8.0
  - path_provider_platform_interface ^2.1.0
  - win32 >=2.1.0 <6.0.0
- permission_handler_android 11.0.5
  - flutter any
  - permission_handler_platform_interface ^3.11.2
- permission_handler_apple 9.1.4
  - flutter any
  - permission_handler_platform_interface ^3.11.2
- permission_handler_platform_interface 3.11.5
  - flutter any
  - meta ^1.3.0
  - plugin_platform_interface ^2.0.0
- permission_handler_windows 0.1.3
  - flutter any
  - permission_handler_platform_interface ^3.11.0
- petitparser 5.4.0
  - meta ^1.9.0
- platform 3.1.2
- plugin_platform_interface 2.1.6
  - meta ^1.3.0
- pointycastle 3.7.3
  - collection ^1.15.0
  - convert ^3.0.0
  - js ^0.6.3
- pool 1.5.1
  - async ^2.5.0
  - stack_trace ^1.10.0
- pub_semver 2.1.4
  - collection ^1.15.0
  - meta ^1.3.0
- pubspec_parse 1.2.3
  - checked_yaml ^2.0.1
  - collection ^1.15.0
  - json_annotation ^4.8.0
  - pub_semver ^2.0.0
  - yaml ^3.0.0
- quiver 3.2.1
  - matcher ^0.12.10
- riverpod 2.4.1
  - meta ^1.9.0
  - stack_trace ^1.10.0
  - state_notifier >=0.7.2 <2.0.0
- riverpod_analyzer_utils 0.4.0
  - analyzer >=5.12.0 <7.0.0
  - collection ^1.16.0
  - crypto ^3.0.2
  - custom_lint_core ^0.5.2
  - freezed_annotation ^2.2.0
  - meta ^1.7.0
  - path ^1.8.0
  - source_span ^1.8.0
- rxdart 0.27.7
- shared_preferences_android 2.2.1
  - flutter any
  - shared_preferences_platform_interface ^2.3.0
- shared_preferences_foundation 2.3.4
  - flutter any
  - shared_preferences_platform_interface ^2.3.0
- shared_preferences_linux 2.3.1
  - file ^6.0.0
  - flutter any
  - path ^1.8.0
  - path_provider_linux ^2.0.0
  - path_provider_platform_interface ^2.0.0
  - shared_preferences_platform_interface ^2.3.0
- shared_preferences_platform_interface 2.3.1
  - flutter any
  - plugin_platform_interface ^2.1.0
- shared_preferences_web 2.2.1
  - flutter any
  - flutter_web_plugins any
  - shared_preferences_platform_interface ^2.3.0
- shared_preferences_windows 2.3.1
  - file ^6.0.0
  - flutter any
  - path ^1.8.0
  - path_provider_platform_interface ^2.0.0
  - path_provider_windows ^2.0.0
  - shared_preferences_platform_interface ^2.3.0
- shelf 1.4.1
  - async ^2.5.0
  - collection ^1.15.0
  - http_parser ^4.0.0
  - path ^1.8.0
  - stack_trace ^1.10.0
  - stream_channel ^2.1.0
- shelf_web_socket 1.0.4
  - shelf ^1.1.0
  - stream_channel ^2.1.0
  - web_socket_channel ^2.0.0
- sky_engine 0.0.99
- source_gen 1.4.0
  - analyzer >=5.2.0 <7.0.0
  - async ^2.5.0
  - build ^2.1.0
  - dart_style ^2.0.0
  - glob ^2.0.0
  - path ^1.8.0
  - source_span ^1.8.0
  - yaml ^3.0.0
- source_span 1.10.0
  - collection ^1.15.0
  - path ^1.8.0
  - term_glyph ^1.2.0
- stack_trace 1.11.0
  - path ^1.8.0
- state_notifier 1.0.0
  - meta ^1.1.8
- stream_channel 2.1.1
  - async ^2.5.0
- stream_transform 2.1.0
- string_scanner 1.2.0
  - source_span ^1.8.0
- term_glyph 1.2.1
- test_api 0.6.0
  - async ^2.5.0
  - boolean_selector ^2.1.0
  - collection ^1.15.0
  - meta ^1.3.0
  - source_span ^1.8.0
  - stack_trace ^1.10.0
  - stream_channel ^2.1.0
  - string_scanner ^1.1.0
  - term_glyph ^1.2.0
- timing 1.0.1
  - json_annotation ^4.3.0
- typed_data 1.3.2
  - collection ^1.15.0
- universal_io 2.2.2
  - collection ^1.17.0
  - meta ^1.9.0
  - typed_data ^1.3.0
- vector_graphics 1.1.7
  - flutter any
  - vector_graphics_codec 1.1.7
- vector_graphics_codec 1.1.7
- vector_graphics_compiler 1.1.7
  - args ^2.3.0
  - meta ^1.7.0
  - path_parsing ^1.0.1
  - xml ^6.3.0
  - vector_graphics_codec 1.1.7
- vector_math 2.1.4
- vm_service 11.10.0
- watcher 1.1.0
  - async ^2.5.0
  - path ^1.8.0
- web 0.1.4-beta
- web_socket_channel 2.4.0
  - async ^2.5.0
  - crypto ^3.0.0
  - stream_channel ^2.1.0
- win32 5.0.9
  - ffi ^2.1.0
- win32_registry 1.1.2
  - ffi ^2.1.0
  - win32 ^5.0.7
- xdg_directories 1.0.3
  - meta ^1.3.0
  - path ^1.8.0
- xml 6.3.0
  - collection ^1.17.0
  - meta ^1.9.0
  - petitparser ^5.4.0
- yaml 3.1.2
  - collection ^1.15.0
  - source_span ^1.8.0
  - string_scanner ^1.1.0
</pre>
</details>

### Steps to reproduce

I've configured my providers like this in main: 

```
 FirebaseUIAuth.configureProviders([
    EmailAuthProvider(),
    GoogleProvider(
      clientId:
          '''xxx'',
    ),
    AppleProvider(),
  ]);
```

I'm using the default SignIn page 

```
SignInScreen()
```

I'm then putting wrong credentials as EMAIL AND PASSWORD (Valid email) and following exception is thrown:

```
Flutter: type 'int' is not a subtype of type 'String' in type cast
flutter: #0      FirebaseAuthHostApi.signInWithCredential
messages.pigeon.dart:1068
<asynchronous suspension>
#1      MethodChannelFirebaseAuth.signInWithCredential
method_channel_firebase_auth.dart:295
<asynchronous suspension>
#2      FirebaseAuth.signInWithCredential
firebase_auth.dart:517
<asynchronous suspension>
```

### Expected Behavior

An error message should be shown instead of a crash due to a wrong cast.
With correct sign in information, it logged in correctly. 

### Actual Behavior

When we try to login, it just spin a circular progress instead of the login button but it's because it crash behind the scene

**Comment by danagbemava-nc** [comment]
Hi @JobiJoba, I just tested the firebase_ui_auth example code and I did not get any issue with the underlying auth package. 
Can you provide a minimal sample in a repo that we can clone so that we can investigate this? 

<img src="https://github.com/firebase/FirebaseUI-Flutter/assets/88313112/2383c28b-5483-4059-a3ec-d752bcb5f69b" width="300"/>

**Comment by JobiJoba** [comment]
@danagbemava-nc 

Hi, that doesn't seems to be an iOS phone that you are trying with. Let me check if it works on Android.

**Comment by JobiJoba** [comment]
I confirm, on Android it works but not iOS :(

**Comment by JobiJoba** [comment]
Hmmm I try the example project and it works ... I'll try to reproduce my issue in a repo. 

I don't know if it's because I'm on a multiple flavors environment or something else.

**Comment by JobiJoba** [comment]
Hi, 

I've created a repo showing the issue.
I did it without multiple flavors because the issue arise there already. 

https://github.com/JobiJoba/issuefirebaseauthuilogin 

If you need anything else please let me know

The error is leading to this 

```
throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
```

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'int' is not a subtype of type 'String' in type cast
#0      FirebaseAuthHostApi.signInWithCredential
messages.pigeon.dart:1068
<asynchronous suspension>
#1      MethodChannelFirebaseAuth.signInWithCredential
method_channel_firebase_auth.dart:295
<asynchronous suspension>
#2      FirebaseAuth.signInWithCredential
firebase_auth.dart:517
<asynchronous suspension>
```

**Comment by JobiJoba** [comment]
Looking deeper into this ... maybe the issue should be created in Firebase Auth itself... what I don't understand is why the example project works. 

In my example repo I try the following which mimic what the Sign in with EmailAuthProvider do 

```
final cred = EmailAuthProvider.credential(
        email: "fdsfsdfsdf@dsfdsf.com", password: "dsdsdsdsdsd");

    FirebaseAuth.instance.signInWithCredential(cred);
```

and I get the same issue, If I use the method signInWithEmail it works as expected. 

Do you think I should create an issue in Firebase Auth repository ?

**Comment by danagbemava-nc** [comment]
Hi @JobiJoba, yes, this should be reported on the flutterfire repo. 

Kindly refile this on the flutterfire repo. 

Closing from here. 

Thank you
