### ISSUE TITLE
🐛 `cancelLabel` should be capitalized for cancel button or have similar `cancelButtonLabel`

### ISSUE THREAD

**Issue by FMorschel** [firebase/FirebaseUI-Flutter#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Localizations

### What platform(s) does this bug affect?

Android, iOS, Web, macOS, Linux, Windows

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
...
  - firebase_ui_auth 1.7.0
  - email_validator ^2.0.1
  - firebase_auth ^4.8.0
  - firebase_core ^2.15.0
  - firebase_dynamic_links ^5.3.4
  - firebase_ui_localizations ^1.6.0
  - firebase_ui_oauth ^1.4.10
  - firebase_ui_shared ^1.3.1
  - flutter any
  - flutter_localizations any
- firebase_ui_localizations 1.6.0
  - flutter any
  - flutter_localizations any
  - path ^1.8.2
...
</pre>
</details>

### Steps to reproduce

Calling `showReauthenticateDialog` is strange with a lowercase cancel button.

### Expected Behavior

Calling `showReauthenticateDialog` and seeing a "Cancel" button.

### Actual Behavior

Calling `showReauthenticateDialog` and seeing a "cancel" button.

### Additional Information

I'm not sure where you are using the `cancelLabel`, but I believe this should not be as it is.

PS: Only tested in `en-us` as of right now.

**Comment by darshankawar** [comment]
Thanks for the report @FMorschel 
I can't replicate using the plugin example using latest version of it ie, 1.8.2.
I see that you are on 1.7.0. Can you upgrade to latest version and confirm ?
If issue persists, can you provide replicable code sample that shows the behavior reported ?

**Comment by lesnitsky** [comment]
This is a valid issue. Fix is in #134
