### ISSUE TITLE
Documentation Missing (https://pub.dev/packages/firebase_ui_auth) 0ct-16-2023

### ISSUE THREAD

**Issue by Topbrains** [firebase/FirebaseUI-Flutter#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Auth

### What platform(s) does this bug affect?

Android, iOS, Web

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
  
</pre>
</details>

### Steps to reproduce

Open https://pub.dev/packages/firebase_ui_auth

Click on any document.

Thee are all missing

### Expected Behavior

Documentation should show up

### Actual Behavior

No show

### Additional Information

Try it!

**Comment by darshankawar** [comment]
https://pub.dev/packages/firebase_ui_auth#docs all links under this section is showing 404.

**Comment by lesnitsky** [comment]
This was fixed by 3063f3ea6331428555b515c79d7264d3e7d332d5, and will be released tomorrow.
