### ISSUE TITLE
🐛 Google signup on iOS

### ISSUE THREAD

**Issue by gbolahan507** [firebase/FirebaseUI-Flutter#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Auth, Firebase UI OAuth Google

### What platform(s) does this bug affect?

iOS

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
    firebase_ui_auth: ^1.9.0
  firebase_ui_oauth_google: ^1.2.12
</pre>
</details>

### Steps to reproduce

Google authentication throwing channel error on IOS

### Expected Behavior

Successful Gmail auth on IOS, it works well on android

### Actual Behavior

Google authentication throwing channel error on IOS

### Additional Information

![Screenshot 2023-10-21 at 17 00 53](https://github.com/firebase/FirebaseUI-Flutter/assets/68135953/dbeffcba-a7b6-4c56-8beb-5ea7e3116394)
![Screenshot 2023-10-21 at 17 01 18](https://github.com/firebase/FirebaseUI-Flutter/assets/68135953/c85a4c31-eab5-420c-9d7f-ba670b697787)

**Comment by darshankawar** [comment]
@gbolahan507 
I am unable to replicate this behavior using [plugin example](https://github.com/firebase/FirebaseUI-Flutter/tree/main/packages/firebase_ui_auth/example) running on iOS. Can you also try using the plugin example and check if you get same error or not ?

**Comment by darshankawar** [comment]
Since there haven't been any recent updates here, I am going to close this issue.

@chtnsngh if you're still experiencing this problem and want to continue the discussion just leave a comment here and we are happy to re-open this.
