### ISSUE TITLE
🐛 [firebase_ui_localizations] Unknown error 

### ISSUE THREAD

**Issue by andreisas06** [firebase/FirebaseUI-Flutter#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Localizations

### What platform(s) does this bug affect?

Web

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
  calendar_date_picker2: ^0.5.2
  collection: ^1.17.1
  equatable: ^2.0.5
  extended_masked_text: ^2.3.1
  file_picker: ^5.3.3
  firebase_analytics_web: ^0.5.4+3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_ui_auth: ^1.4.3
  firebase_ui_localizations: ^1.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  go_router: ^11.1.1
  google_fonts: ^4.0.4
  intl: ^0.18.0
  isoweek: ^1.1.4
  pdf: ^3.10.4
  rxdart: ^0.27.7
  screenshot: ^2.1.0
  uuid: ^3.0.7
</pre>
</details>

### Steps to reproduce

Not sure how to reproduce this error. I used firebase_ui_localizations to translate Firebase UI Auth screen from the default english to dutch. It seems everything is translated as expected except for the error below:
<img width="402" alt="31d7e6ed-9e9b-483f-955c-15f700f18723" src="https://github.com/firebase/FirebaseUI-Flutter/assets/48185017/883f37f1-dcca-4134-9ed2-f233572e2196">

I can't seem to reproduce this error as it pop, I encountered it a few times.

I tried: non-existent username and password, non-existent username and existing password and vice versa, and the error messages are translated, except the error message in the image. I couldn't find a pattern to reproduce this error.

### Expected Behavior

The error message to be translated, like every other field in the Firebase UI Auth screen currently is.

### Actual Behavior

That specific error message from the picture provided isn't translated to dutch, yet the other fields are.

### Additional Information

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.13.7, on macOS 14.0 23A344 darwin-arm64, locale en-NL)
    • Flutter version 3.13.7 on channel stable at /Users/andreisas/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (3 weeks ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/andreisas/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @andreisas06, do you get this issue on either android or iOS as well? Do you also get this issue with the plugin example app? 

Please also provide the output of `flutter pub deps -- --style=compact`. 

Thank you

**Comment by andreisas06** [comment]
Nope, the project that I am working on is exclusively a Web project, it doesn't have the build files for Android or IOS.
Here is the output you requested:

Dart SDK 3.1.3
Flutter SDK 3.13.7
zwierink_workspace 0.0.0

dev dependencies:
- melos 3.1.1 [ansi_styles args cli_launcher cli_util collection conventional_commit file glob graphs http meta mustache_template path platform pool prompts pub_semver pub_updater pubspec string_scanner yaml yaml_edit]

transitive dependencies:
- ansi_styles 0.3.2+1
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- charcode 1.3.1
- cli_launcher 0.3.1 [path yaml]
- cli_util 0.4.0 [meta path]
- collection 1.18.0
- conventional_commit 0.6.0+1
- file 6.1.4 [meta path]
- glob 2.1.2 [async collection file path string_scanner]
- graphs 2.3.1 [collection]
- http 1.1.0 [async http_parser meta]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- io 1.0.4 [meta path string_scanner]
- json_annotation 4.8.1 [meta]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- meta 1.9.1
- mustache_template 2.0.0
- path 1.8.3
- platform 3.1.2
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- prompts 2.0.0 [charcode io]
- pub_semver 2.1.4 [collection meta]
- pub_updater 0.3.1 [http json_annotation process pub_semver]
- pubspec 2.3.0 [path pub_semver yaml uri]
- quiver 3.2.1 [matcher]
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- uri 1.0.0 [matcher quiver]
- yaml 3.1.2 [collection source_span string_scanner]
- yaml_edit 2.1.1 [collection meta source_span yaml]

**Comment by danagbemava-nc** [comment]
Hi @andreisas06, I am not seeing the versions of the firebase_ui_* packages you're using in your project from the output your provided above. 

What version you're of the firebase_ui_* packages are you using in your project? Also, what version of auth do you have in your project? 

From what I'm seeing in the translations for dutch, it seems like the account not found error should have been translated, but the error seems different that what you are showing. See https://github.com/firebase/FirebaseUI-Flutter/blob/1a0385c3aa61e1bf9b67e8d42e72f29004074ff1/packages/firebase_ui_localizations/lib/src/lang/nl.dart#L245

**Comment by andreisas06** [comment]
firebase_analytics_web: ^0.5.4+3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_ui_auth: ^1.4.3
  firebase_ui_localizations: ^1.6.1
  
  These are my firebase dependencies.
  
  Yes it should have been translated since the other parts of firebase ui are translated.
  
  Is there any other thing I can provide you with to narrow down the issue and give you more context?

**Comment by danagbemava-nc** [comment]
Hi @andreisas06, you are using older versions of the firebase packages, can you upgrade to the latest versions to see if you still have this issue?

**Comment by danagbemava-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
