### ISSUE TITLE
🐛 [firebase_ui_auth] Version 1.4.0 is causing compilation error

### ISSUE THREAD

**Issue by outdoorapps** [firebase/FirebaseUI-Flutter#19]
The recent changes in version 1.4.0 are causing the following compilation error:

`../../.pub-cache/hosted/pub.dev/firebase_ui_auth-1.4.0/lib/src/screens/profile_screen.dart:393:19: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
            const Row(
                  ^^^`

The `const` keyword wasn't there in version 1.3.0.

**Comment by lesnitsky** [comment]
Fixed by https://github.com/firebase/flutterfire/pull/10957
