### ISSUE TITLE
Icons on profile screen does not appear

### ISSUE THREAD

**Issue by abah19vo** [firebase/FirebaseUI-Flutter#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Auth

### What platform(s) does this bug affect?

Android, iOS, Web, macOS, Linux

### List of dependencies used.

<details>
<summary>Icons on profile screen does not appear after configuring them </summary>
<pre>
 In the profile screen the configured providers icons have a question mark. this appeared for google provider and apple provider
</pre>
</details>

<img src="https://github.com/firebase/FirebaseUI-Flutter/assets/70108548/f234fde4-466c-4d2a-b54c-8ec5e92a9fe6" width="300" /> 

### Steps to reproduce

use google or apple as a provider and configure them and then they will become a question mark

### Expected Behavior

normal icon on the inlogging methods parts

### Actual Behavior

question marks instead
<img src="https://github.com/firebase/FirebaseUI-Flutter/assets/70108548/ae420e61-4d40-4cdf-82e0-fa5bed471270" width="300"/>

**Comment by ReallySmallSoftware** [comment]
I can verify that I am seeing this also

**Comment by danagbemava-nc** [comment]
Hi @abah19vo, what version of `firebase_ui_auth` are you using?

**Comment by abah19vo** [comment]
> Hi @abah19vo, what version of `firebase_ui_auth` are you using?

The newest one

**Comment by danagbemava-nc** [comment]
Hi @abah19vo, using the plugin example app the google icon is properly rendered for me. Do you see any errors in your console? 

Please also share the output of `flutter pub deps -- --style=compact`. 

Also, do you get the same issue with the plugin example app?

<img src="https://github.com/firebase/FirebaseUI-Flutter/assets/88313112/865f3a9c-c630-45ad-b625-f5ba0e724951" width="300"/>

**Comment by danagbemava-nc** [comment]
Hi @abah19vo, coming back to this, have you added the social icons package to your pubspec.yaml? See https://github.com/firebase/FirebaseUI-Flutter/tree/main/packages/firebase_ui_auth#profile-screen-icons for how you can do this

**Comment by danagbemava-nc** [comment]
Closing this since it seems like the issue lies in not including the social icons fonts in the project.
