### ISSUE TITLE
🐛 'Sent verification email' missing localization

### ISSUE THREAD

**Issue by apnnux** [firebase/FirebaseUI-Flutter#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Auth, Firebase UI Localizations

### What platform(s) does this bug affect?

Android, iOS, Web, macOS, Linux, Windows

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
  
</pre>
</details>

### Steps to reproduce

Go to profile page before verification email

### Expected Behavior

Localized label

### Actual Behavior

Hardcoded string in button

![image](https://github.com/firebase/FirebaseUI-Flutter/assets/58971732/c9db9f77-21ce-43d3-9c93-9f5a4f356585)

**Comment by danagbemava-nc** [comment]
Hi @apnnux, what file is the screenshot of the code from? 

In the future, it would be best if you could provide the github permalink to such code snippets.

**Comment by lesnitsky** [comment]
[label: 'Send verification email',](https://github.com/firebase/FirebaseUI-Flutter/blob/c0612cfd71dc5ea2448ba73882b39a9766b97a98/packages/firebase_ui_auth/lib/src/screens/profile_screen.dart#L442)
