### ISSUE TITLE
🐛 Error: A value of type 'int?' can't be returned from a function with return type 'int' because 'int?' is nullable and 'int' isn't.

### ISSUE THREAD

**Issue by salar-dev** [firebase/FirebaseUI-Flutter#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Firestore

### What platform(s) does this bug affect?

iOS

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
  
</pre>
</details>

### Steps to reproduce

../../../../.pub-cache/hosted/pub.dev/firebase_ui_firestore-1.6.0/lib/src/table_builder.dart:874:71: Error: A value of type 'int?' can't be returned from a function with return type 'int' because 'int?' is nullable and 'int' isn't.

### Expected Behavior

Shod Build Without any error

### Actual Behavior

When Build App on ios I get this error
../../../../.pub-cache/hosted/pub.dev/firebase_ui_firestore-1.6.0/lib/src/table_builder.dart:874:71: Error: A value of type 'int?' can't be returned from a function with return type 'int' because 'int?' is nullable and 'int' isn't.

### Additional Information

Flutter (Channel stable, 3.16.5, on macOS 14.1.1 23B81 darwin-arm64, locale
    en-IQ)
    • Flutter version 3.16.5 on channel stable at
      /Users/salardev/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (2 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/salardev/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • iPhone (mobile)            • 00008020-001A21392ED8003A            • ios
      • iOS 17.1.1 21B91
    • iPhone 15 Pro Max (mobile) • 655CBA25-15C1-4728-8CF4-9FF65CC2BFB0 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by muhammadayed** [comment]
any update related this issue ?

**Comment by lesnitsky** [comment]
This was fixed in #246, just not yet released.
You could install the latest firebase_ui_firestore with the fix from the repo:

```
dependencies:
  firebase_ui_firestore:
    git:
      url: https://github.com/firebase/FirebaseUI-Flutter.git
      path: packages/firebase_ui_firestore
```

**Comment by muhammadayed** [comment]
thanks alot, working fine now

**Comment by danagbemava-nc** [comment]
Closing this since this issue has already been fixed. 

Until the fix is released on pub.dev, anyone who runs into this issue can use https://github.com/firebase/FirebaseUI-Flutter/issues/248#issuecomment-1879270120

**Comment by BirjuVachhani** [comment]
When will this be published on pub.dev? I am using this in package and I can't use the git source there.

**Comment by lesnitsky** [comment]
It is now available on pub.
