### ISSUE TITLE
🐛 Google SignIn fails with an Internal Error

### ISSUE THREAD

**Issue by kroikie** [firebase/FirebaseUI-Flutter#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Auth

### What platform(s) does this bug affect?

Android

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
  flutter pub deps -s list
Dart SDK 3.2.3
Flutter SDK 3.16.5
pedro 1.0.0+1

dependencies:
- flutter 0.0.0
  - characters 1.3.0
  - collection 1.18.0
  - material_color_utilities 0.5.0
  - meta 1.10.0
  - vector_math 2.1.4
  - web 0.3.0
  - sky_engine any
- async 2.11.0
  - collection ^1.15.0
  - meta ^1.1.7
- audioplayers 5.2.1
  - audioplayers_android ^4.0.3
  - audioplayers_darwin ^5.0.2
  - audioplayers_linux ^3.1.0
  - audioplayers_platform_interface ^6.1.0
  - audioplayers_web ^4.1.0
  - audioplayers_windows ^3.1.0
  - file >=6.1.0 <8.0.0
  - flutter any
  - http >=0.13.1 <2.0.0
  - meta ^1.7.0
  - path_provider ^2.0.12
  - synchronized ^3.0.0
  - uuid >=3.0.7 <5.0.0
- go_router 12.1.3
  - collection ^1.15.0
  - flutter any
  - flutter_web_plugins any
  - logging ^1.0.0
  - meta ^1.7.0
- logging 1.2.0
- provider 6.1.1
  - collection ^1.15.0
  - flutter any
  - nested ^1.0.0
- shared_preferences 2.2.2
  - flutter any
  - shared_preferences_android ^2.1.0
  - shared_preferences_foundation ^2.2.0
  - shared_preferences_linux ^2.2.0
  - shared_preferences_platform_interface ^2.3.0
  - shared_preferences_web ^2.1.0
  - shared_preferences_windows ^2.2.0
- cupertino_icons 1.0.6
- firebase_core 2.24.2
  - firebase_core_platform_interface ^5.0.0
  - firebase_core_web ^2.10.0
  - flutter any
  - meta ^1.8.0
- cloud_firestore 4.14.0
  - cloud_firestore_platform_interface ^6.1.0
  - cloud_firestore_web ^3.9.0
  - collection ^1.0.0
  - firebase_core ^2.24.2
  - firebase_core_platform_interface ^5.0.0
  - flutter any
  - meta ^1.8.0
- firebase_ui_firestore 1.6.1
  - cloud_firestore ^4.13.6
  - firebase_ui_localizations ^1.10.1
  - firebase_ui_shared ^1.4.1
  - flutter any
- cloud_functions 4.6.0
  - cloud_functions_platform_interface ^5.5.11
  - cloud_functions_web ^4.6.11
  - firebase_core ^2.24.2
  - firebase_core_platform_interface ^5.0.0
  - flutter any
- firebase_auth 4.16.0
  - firebase_auth_platform_interface ^7.0.9
  - firebase_auth_web ^5.8.13
  - firebase_core ^2.24.2
  - firebase_core_platform_interface ^5.0.0
  - flutter any
  - meta ^1.8.0
- firebase_ui_auth 1.12.1
  - email_validator ^2.1.17
  - firebase_auth ^4.15.3
  - firebase_core ^2.24.2
  - firebase_dynamic_links ^5.4.8
  - firebase_ui_localizations ^1.10.1
  - firebase_ui_oauth ^1.4.17
  - firebase_ui_shared ^1.4.1
  - flutter any
  - flutter_localizations any
  - meta ^1.10.0
- google_sign_in 6.2.1
  - flutter any
  - google_sign_in_android ^6.1.0
  - google_sign_in_ios ^5.7.0
  - google_sign_in_platform_interface ^2.4.0
  - google_sign_in_web ^0.12.0
- firebase_ui_oauth_google 1.2.17
  - firebase_auth ^4.15.3
  - firebase_ui_oauth ^1.4.17
  - flutter any
  - google_sign_in ^6.2.1
- rxdart 0.27.7

dev dependencies:
- flutter_lints 3.0.1
  - lints ^3.0.0
- flutter_test 0.0.0
  - flutter any
  - test_api 0.6.1
  - matcher 0.12.16
  - path 1.8.3
  - fake_async 1.3.1
  - clock 1.1.1
  - stack_trace 1.11.1
  - vector_math 2.1.4
  - async 2.11.0
  - boolean_selector 2.1.1
  - characters 1.3.0
  - collection 1.18.0
  - material_color_utilities 0.5.0
  - meta 1.10.0
  - source_span 1.10.0
  - stream_channel 2.1.2
  - string_scanner 1.2.0
  - term_glyph 1.2.1
  - web 0.3.0
- flutter_launcher_icons 0.13.1
  - args ^2.3.2
  - checked_yaml ^2.0.2
  - cli_util ^0.4.0
  - image ^4.0.15
  - json_annotation ^4.8.0
  - path ^1.8.2
  - yaml ^3.1.1
- test 1.24.9
  - analyzer >=5.12.0 <7.0.0
  - async ^2.5.0
  - boolean_selector ^2.1.0
  - collection ^1.15.0
  - coverage ^1.0.1
  - http_multi_server ^3.0.0
  - io ^1.0.0
  - js ^0.6.4
  - matcher >=0.12.16 <0.12.17
  - node_preamble ^2.0.0
  - package_config ^2.0.0
  - path ^1.8.0
  - pool ^1.5.0
  - shelf ^1.0.0
  - shelf_packages_handler ^3.0.0
  - shelf_static ^1.0.0
  - shelf_web_socket ^1.0.0
  - source_span ^1.8.0
  - stack_trace ^1.10.0
  - stream_channel ^2.1.0
  - test_api 0.6.1
  - test_core 0.5.9
  - typed_data ^1.3.0
  - web_socket_channel ^2.0.0
  - webkit_inspection_protocol ^1.0.0
  - yaml ^3.0.0

transitive dependencies:
- _fe_analyzer_shared 64.0.0
  - meta ^1.9.0
- _flutterfire_internals 1.3.16
  - collection ^1.0.0
  - firebase_core ^2.24.2
  - firebase_core_platform_interface ^5.0.0
  - flutter any
  - meta ^1.8.0
- analyzer 6.2.0
  - _fe_analyzer_shared ^64.0.0
  - collection ^1.17.0
  - convert ^3.0.0
  - crypto ^3.0.0
  - glob ^2.0.0
  - meta ^1.7.0
  - package_config ^2.0.0
  - path ^1.8.0
  - pub_semver ^2.0.0
  - source_span ^1.8.0
  - watcher ^1.0.0
  - yaml ^3.0.0
- archive 3.4.10
  - crypto ^3.0.3
  - path ^1.8.0
  - pointycastle ^3.7.3
- args 2.4.2
- audioplayers_android 4.0.3
  - audioplayers_platform_interface ^6.1.0
  - flutter any
- audioplayers_darwin 5.0.2
  - audioplayers_platform_interface ^6.1.0
  - flutter any
- audioplayers_linux 3.1.0
  - audioplayers_platform_interface ^6.1.0
  - flutter any
- audioplayers_platform_interface 6.1.0
  - flutter any
  - meta ^1.7.0
  - plugin_platform_interface ^2.0.2
- audioplayers_web 4.1.0
  - audioplayers_platform_interface ^6.1.0
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.4
- audioplayers_windows 3.1.0
  - audioplayers_platform_interface ^6.1.0
  - flutter any
- boolean_selector 2.1.1
  - source_span ^1.8.0
  - string_scanner ^1.1.0
- characters 1.3.0
- checked_yaml 2.0.3
  - json_annotation ^4.3.0
  - source_span ^1.8.0
  - yaml ^3.0.0
- cli_util 0.4.1
  - meta ^1.3.0
  - path ^1.8.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.0
  - _flutterfire_internals ^1.3.16
  - collection ^1.15.0
  - firebase_core ^2.24.2
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- cloud_firestore_web 3.9.0
  - _flutterfire_internals ^1.3.16
  - cloud_firestore_platform_interface ^6.1.0
  - collection ^1.0.0
  - firebase_core ^2.24.2
  - firebase_core_web ^2.10.0
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
- cloud_functions_platform_interface 5.5.11
  - firebase_core ^2.24.2
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- cloud_functions_web 4.6.11
  - cloud_functions_platform_interface ^5.5.11
  - firebase_core ^2.24.2
  - firebase_core_web ^2.10.0
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
- collection 1.18.0
- convert 3.1.1
  - typed_data ^1.3.0
- coverage 1.7.2
  - args ^2.0.0
  - logging ^1.0.0
  - package_config ^2.0.0
  - path ^1.8.0
  - source_maps ^0.10.10
  - stack_trace ^1.10.0
  - vm_service >=12.0.0 <15.0.0
- crypto 3.0.3
  - typed_data ^1.3.0
- desktop_webview_auth 0.0.14
  - crypto ^3.0.3
  - flutter any
  - http ^1.0.0
  - flutter_web_plugins any
  - plugin_platform_interface ^2.1.4
- email_validator 2.1.17
- fake_async 1.3.1
  - clock ^1.1.0
  - collection ^1.15.0
- ffi 2.1.0
- file 7.0.0
  - meta ^1.9.1
  - path ^1.8.3
- firebase_auth_platform_interface 7.0.9
  - _flutterfire_internals ^1.3.16
  - collection ^1.16.0
  - firebase_core ^2.24.2
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_auth_web 5.8.13
  - firebase_auth_platform_interface ^7.0.9
  - firebase_core ^2.24.2
  - firebase_core_web ^2.10.0
  - flutter any
  - flutter_web_plugins any
  - http_parser ^4.0.0
  - js ^0.6.3
  - meta ^1.8.0
- firebase_core_platform_interface 5.0.0
  - collection ^1.0.0
  - flutter any
  - flutter_test any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_core_web 2.10.0
  - firebase_core_platform_interface ^5.0.0
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
  - meta ^1.8.0
- firebase_dynamic_links 5.4.8
  - firebase_core ^2.24.2
  - firebase_core_platform_interface ^5.0.0
  - firebase_dynamic_links_platform_interface ^0.2.6+16
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_dynamic_links_platform_interface 0.2.6+16
  - _flutterfire_internals ^1.3.16
  - firebase_core ^2.24.2
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_ui_localizations 1.10.1
  - flutter any
  - flutter_localizations any
  - path ^1.8.3
- firebase_ui_oauth 1.4.17
  - desktop_webview_auth ^0.0.14
  - firebase_auth ^4.15.3
  - firebase_ui_auth ^1.12.1
  - firebase_ui_shared ^1.4.1
  - flutter_svg ^2.0.9
  - flutter any
- firebase_ui_shared 1.4.1
  - flutter any
- flutter_localizations 0.0.0
  - flutter any
  - intl 0.18.1
  - characters 1.3.0
  - clock 1.1.1
  - collection 1.18.0
  - material_color_utilities 0.5.0
  - meta 1.10.0
  - path 1.8.3
  - vector_math 2.1.4
  - web 0.3.0
- flutter_svg 2.0.9
  - flutter any
  - vector_graphics ^1.1.9+1
  - vector_graphics_codec ^1.1.9+1
  - vector_graphics_compiler ^1.1.9+1
- flutter_web_plugins 0.0.0
  - flutter any
  - characters 1.3.0
  - collection 1.18.0
  - material_color_utilities 0.5.0
  - meta 1.10.0
  - vector_math 2.1.4
  - web 0.3.0
- frontend_server_client 3.2.0
  - async ^2.5.0
  - path ^1.8.0
- glob 2.1.2
  - async ^2.5.0
  - collection ^1.15.0
  - file >=6.1.3 <8.0.0
  - path ^1.8.0
  - string_scanner ^1.1.0
- google_identity_services_web 0.3.0+2
  - meta ^1.3.0
  - web >=0.3.0 <0.5.0
- google_sign_in_android 6.1.21
  - flutter any
  - google_sign_in_platform_interface ^2.2.0
- google_sign_in_ios 5.7.3
  - flutter any
  - google_sign_in_platform_interface ^2.2.0
- google_sign_in_platform_interface 2.4.5
  - flutter any
  - plugin_platform_interface ^2.1.7
- google_sign_in_web 0.12.3+2
  - flutter any
  - flutter_web_plugins any
  - google_identity_services_web ^0.3.0
  - google_sign_in_platform_interface ^2.4.0
  - http >=0.13.0 <2.0.0
  - web >=0.3.0 <0.5.0
- http 1.1.2
  - async ^2.5.0
  - http_parser ^4.0.0
  - meta ^1.3.0
  - web >=0.3.0 <0.5.0
- http_multi_server 3.2.1
  - async ^2.5.0
- http_parser 4.0.2
  - collection ^1.15.0
  - source_span ^1.8.0
  - string_scanner ^1.1.0
  - typed_data ^1.3.0
- image 4.1.3
  - archive ^3.4.0
  - meta ^1.3.0
  - xml ^6.0.1
- intl 0.18.1
  - clock ^1.1.0
  - meta ^1.0.2
  - path ^1.8.0
- io 1.0.4
  - meta ^1.3.0
  - path ^1.8.0
  - string_scanner ^1.1.0
- js 0.6.7
  - meta ^1.7.0
- json_annotation 4.8.1
  - meta ^1.4.0
- lints 3.0.0
- matcher 0.12.16
  - async ^2.10.0
  - meta ^1.8.0
  - stack_trace ^1.10.0
  - term_glyph ^1.2.0
  - test_api >=0.5.0 <0.7.0
- material_color_utilities 0.5.0
  - collection ^1.15.0
- meta 1.10.0
- mime 1.0.4
- nested 1.0.0
  - flutter any
- node_preamble 2.0.2
- package_config 2.1.0
  - path ^1.8.0
- path 1.8.3
- path_parsing 1.0.1
  - vector_math ^2.1.0
  - meta ^1.3.0
- path_provider 2.1.1
  - flutter any
  - path_provider_android ^2.1.0
  - path_provider_foundation ^2.3.0
  - path_provider_linux ^2.2.0
  - path_provider_platform_interface ^2.1.0
  - path_provider_windows ^2.2.0
- path_provider_android 2.2.2
  - flutter any
  - path_provider_platform_interface ^2.1.0
- path_provider_foundation 2.3.1
  - flutter any
  - path_provider_platform_interface ^2.1.0
- path_provider_linux 2.2.1
  - ffi >=1.1.2 <3.0.0
  - flutter any
  - path ^1.8.0
  - path_provider_platform_interface ^2.1.0
  - xdg_directories >=0.2.0 <2.0.0
- path_provider_platform_interface 2.1.1
  - flutter any
  - platform ^3.0.0
  - plugin_platform_interface ^2.1.0
- path_provider_windows 2.2.1
  - ffi ^2.0.0
  - flutter any
  - path ^1.8.0
  - path_provider_platform_interface ^2.1.0
  - win32 >=2.1.0 <6.0.0
- petitparser 6.0.2
  - meta ^1.9.0
- platform 3.1.4
- plugin_platform_interface 2.1.8
  - meta ^1.3.0
- pointycastle 3.7.3
  - collection ^1.15.0
  - convert ^3.0.0
  - js ^0.6.3
- pool 1.5.1
  - async ^2.5.0
  - stack_trace ^1.10.0
- pub_semver 2.1.4
  - collection ^1.15.0
  - meta ^1.3.0
- shared_preferences_android 2.2.1
  - flutter any
  - shared_preferences_platform_interface ^2.3.0
- shared_preferences_foundation 2.3.4
  - flutter any
  - shared_preferences_platform_interface ^2.3.0
- shared_preferences_linux 2.3.2
  - file >=6.0.0 <8.0.0
  - flutter any
  - path ^1.8.0
  - path_provider_linux ^2.0.0
  - path_provider_platform_interface ^2.0.0
  - shared_preferences_platform_interface ^2.3.0
- shared_preferences_platform_interface 2.3.1
  - flutter any
  - plugin_platform_interface ^2.1.0
- shared_preferences_web 2.2.2
  - flutter any
  - flutter_web_plugins any
  - shared_preferences_platform_interface ^2.3.0
  - web >=0.3.0 <0.5.0
- shared_preferences_windows 2.3.2
  - file >=6.0.0 <8.0.0
  - flutter any
  - path ^1.8.0
  - path_provider_platform_interface ^2.0.0
  - path_provider_windows ^2.0.0
  - shared_preferences_platform_interface ^2.3.0
- shelf 1.4.1
  - async ^2.5.0
  - collection ^1.15.0
  - http_parser ^4.0.0
  - path ^1.8.0
  - stack_trace ^1.10.0
  - stream_channel ^2.1.0
- shelf_packages_handler 3.0.2
  - path ^1.8.0
  - shelf ^1.0.0
  - shelf_static ^1.0.0
- shelf_static 1.1.2
  - convert ^3.0.0
  - http_parser ^4.0.0
  - mime ^1.0.0
  - path ^1.8.0
  - shelf ^1.1.2
- shelf_web_socket 1.0.4
  - shelf ^1.1.0
  - stream_channel ^2.1.0
  - web_socket_channel ^2.0.0
- sky_engine 0.0.99
- source_map_stack_trace 2.1.1
  - path ^1.8.0
  - source_maps ^0.10.10
  - stack_trace ^1.10.0
- source_maps 0.10.12
  - source_span ^1.8.0
- source_span 1.10.0
  - collection ^1.15.0
  - path ^1.8.0
  - term_glyph ^1.2.0
- sprintf 7.0.0
- stack_trace 1.11.1
  - path ^1.8.0
- stream_channel 2.1.2
  - async ^2.5.0
- string_scanner 1.2.0
  - source_span ^1.8.0
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1
  - async ^2.5.0
  - boolean_selector ^2.1.0
  - collection ^1.15.0
  - meta ^1.3.0
  - source_span ^1.8.0
  - stack_trace ^1.10.0
  - stream_channel ^2.1.0
  - string_scanner ^1.1.0
  - term_glyph ^1.2.0
- test_core 0.5.9
  - analyzer >=3.3.0 <7.0.0
  - args ^2.0.0
  - async ^2.5.0
  - boolean_selector ^2.1.0
  - collection ^1.15.0
  - coverage ^1.0.0
  - frontend_server_client >=3.2.0 <4.0.0
  - glob ^2.0.0
  - io ^1.0.0
  - meta ^1.3.0
  - package_config ^2.0.0
  - path ^1.8.0
  - pool ^1.5.0
  - source_map_stack_trace ^2.1.0
  - source_maps ^0.10.10
  - source_span ^1.8.0
  - stack_trace ^1.10.0
  - stream_channel ^2.1.0
  - test_api 0.6.1
  - vm_service >=6.0.0 <14.0.0
  - yaml ^3.0.0
- typed_data 1.3.2
  - collection ^1.15.0
- uuid 4.2.2
  - crypto ^3.0.0
  - sprintf ^7.0.0
  - meta ^1.9.1
- vector_graphics 1.1.9+2
  - flutter any
  - vector_graphics_codec 1.1.9+2
- vector_graphics_codec 1.1.9+2
- vector_graphics_compiler 1.1.9+2
  - args ^2.3.0
  - meta ^1.7.0
  - path_parsing ^1.0.1
  - xml ^6.3.0
  - vector_graphics_codec 1.1.9+2
  - path ^1.8.0
- vector_math 2.1.4
- vm_service 13.0.0
- watcher 1.1.0
  - async ^2.5.0
  - path ^1.8.0
- web 0.3.0
- web_socket_channel 2.4.0
  - async ^2.5.0
  - crypto ^3.0.0
  - stream_channel ^2.1.0
- webkit_inspection_protocol 1.2.1
  - logging ^1.0.0
- win32 5.2.0
  - ffi ^2.1.0
- xdg_directories 1.0.4
  - meta ^1.3.0
  - path ^1.8.0
- xml 6.5.0
  - collection ^1.18.0
  - meta ^1.9.0
  - petitparser ^6.0.0
- yaml 3.1.2
  - collection ^1.15.0
  - source_span ^1.8.0
  - string_scanner ^1.1.0
</pre>
</details>

### Steps to reproduce

- Start Firebase Emulator (with auth)
- `useAuthEmulator`
- Use SignInScreen with GoogleProvider
- Sign In with Google
- Observe Error after signing in:
    
```
An internal error has occurred. [ The Auth Emulator only supports sign-in with google.com id_token, 
not access_token. Please update your code to use id_token. ]
```

### Expected Behavior

Sign in would complete as with the same setup on iOS.

### Actual Behavior

<img width="371" alt="Screenshot 2024-02-04 at 3 36 43 PM" src="https://github.com/firebase/FirebaseUI-Flutter/assets/2370200/e4439d4d-b6b2-4b73-984a-7fc7d320eee1">

### Additional Information

I have added the SHA-1 to the Firebase project. Same setup works with the iOS simulator.

**Comment by danagbemava-nc** [comment]
Hi @kroikie, I just tested the firebase ui auth example app with the firebase emulator and google sign in works just fine for me. Can you try upgrading to the latest version of the plugins to see if you still experience this issue? 

https://github.com/firebase/FirebaseUI-Flutter/assets/88313112/c4f39bdd-c5bc-46e2-890a-3a5a38e7e4a6

<img width="1487" alt="Screenshot 2024-02-05 at 15 53 29" src="https://github.com/firebase/FirebaseUI-Flutter/assets/88313112/33175c9a-0a23-4e4e-a891-b83e37bd6384">

Also, are you using the plugin example as is? Or are you running a custom version of the example app? If so, could you provide a complete minimal sample so that we can investigate this?
