### ISSUE TITLE
super class OAuthProvider has no desktopSignIn method

### ISSUE THREAD

**Issue by graemep-nz** [firebase/FirebaseUI-Flutter#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI OAuth Google

### What platform(s) does this bug affect?

Web

### List of dependencies used.

...

### Steps to reproduce

This commit made build fail for web

https://github.com/firebase/FirebaseUI-Flutter/commit/72571a0dd20181cabfc1f63d52e903e754399496
The super class OAuthProvider has no desktopSignIn method

```dart
@override
  void desktopSignIn(AuthAction action) {
    // google_sign_in supports macOS, so mobile auth flow works.
    if (defaultTargetPlatform == TargetPlatform.macOS) {
      mobileSignIn(action);
    } else {
      super.desktopSignIn(action);
    }
  }
```

![image](https://github.com/firebase/FirebaseUI-Flutter/assets/39331416/5d2fc9bf-e728-4c13-82cb-8c3795f3610b)

### Expected Behavior

no compilation error

### Actual Behavior

build fails

### Additional Information

is there some way that code which doesn't build can be prevented from being committed to the repo

**Comment by victorcode1** [comment]
I have problem

**Comment by graemep-nz** [comment]
> I have problem

just comment out the call to super.desktopSignIn for now, I'm sure this will be fixed soon.

**Comment by danagbemava-nc** [comment]
Reproducible using the firebase_ui_auth example app. 

To reproduce, run the example app on web

```
Launching lib\main.dart on Chrome in debug mode...
../../../AppData/Local/Pub/Cache/hosted/pub.dev/firebase_ui_oauth_google-1.3.0/lib/src/provider.dart:97:13: Error: Superclass has no method named 'desktopSignIn'.
      super.desktopSignIn(action);
            ^^^^^^^^^^^^^
Failed to compile application.
```

**Comment by russellwheatley** [comment]
The fix has already been merged to master: https://github.com/firebase/FirebaseUI-Flutter/pull/294
