### ISSUE TITLE
🐛 No access to oauthAccessToken on signInWithIdp request

### ISSUE THREAD

**Issue by bedardjo** [firebase/FirebaseUI-Flutter#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI OAuth Google

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
dependencies:
- flutter 0.0.0
  - characters 1.3.0
  - collection 1.18.0
  - material_color_utilities 0.8.0
  - meta 1.11.0
  - vector_math 2.1.4
  - sky_engine any
- protobuf 3.1.0
  - collection ^1.15.0
  - fixnum ^1.0.0
  - meta ^1.7.0
- http 1.2.1
  - async ^2.5.0
  - http_parser ^4.0.0
  - meta ^1.3.0
  - web ^0.5.0
- cupertino_icons 1.0.6
- firebase_core 2.27.1
  - firebase_core_platform_interface ^5.0.0
  - firebase_core_web ^2.12.0
  - flutter any
  - meta ^1.8.0
- firebase_auth 4.17.9
  - firebase_auth_platform_interface ^7.1.9
  - firebase_auth_web ^5.10.0
  - firebase_core ^2.27.1
  - firebase_core_platform_interface ^5.0.0
  - flutter any
  - meta ^1.8.0
- firebase_ui_auth 1.13.1
  - email_validator ^2.1.17
  - firebase_auth ^4.17.5
  - firebase_core ^2.25.4
  - firebase_dynamic_links ^5.4.14
  - firebase_ui_localizations ^1.10.2
  - firebase_ui_oauth ^1.5.1
  - firebase_ui_shared ^1.4.1
  - flutter any
  - flutter_localizations any
  - meta ^1.10.0
- firebase_ui_oauth_google 1.3.1
  - firebase_auth ^4.17.5
  - firebase_ui_oauth ^1.5.1
  - flutter any
  - google_sign_in ^6.2.1
- firebase_database 10.4.10
  - firebase_core ^2.27.1
  - firebase_core_platform_interface ^5.0.0
  - firebase_database_platform_interface ^0.2.5+26
  - firebase_database_web ^0.2.3+26
  - flutter any
- uuid 4.3.3
  - crypto ^3.0.0
  - sprintf ^7.0.0
  - meta ^1.10.0
  - fixnum ^1.1.0
- firebase_storage 11.6.10
  - firebase_core ^2.27.1
  - firebase_core_platform_interface ^5.0.0
  - firebase_storage_platform_interface ^5.1.13
  - firebase_storage_web ^3.8.0
  - flutter any
- google_sign_in 6.2.1
  - flutter any
  - google_sign_in_android ^6.1.0
  - google_sign_in_ios ^5.7.0
  - google_sign_in_platform_interface ^2.4.0
  - google_sign_in_web ^0.12.0

dev dependencies:
- flutter_test 0.0.0
  - flutter any
  - test_api 0.6.1
  - matcher 0.12.16+1
  - path 1.9.0
  - fake_async 1.3.1
  - clock 1.1.1
  - stack_trace 1.11.1
  - vector_math 2.1.4
  - leak_tracker_flutter_testing 2.0.1
  - async 2.11.0
  - boolean_selector 2.1.1
  - characters 1.3.0
  - collection 1.18.0
  - leak_tracker 10.0.0
  - leak_tracker_testing 2.0.1
  - material_color_utilities 0.8.0
  - meta 1.11.0
  - source_span 1.10.0
  - stream_channel 2.1.2
  - string_scanner 1.2.0
  - term_glyph 1.2.1
  - vm_service 13.0.0
- flutter_lints 3.0.1
  - lints ^3.0.0

transitive dependencies:
- _flutterfire_internals 1.3.26
  - collection ^1.0.0
  - firebase_core ^2.27.1
  - firebase_core_platform_interface ^5.0.0
  - flutter any
  - meta ^1.8.0
- args 2.4.2
- async 2.11.0
  - collection ^1.15.0
  - meta ^1.1.7
- boolean_selector 2.1.1
  - source_span ^1.8.0
  - string_scanner ^1.1.0
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- crypto 3.0.3
  - typed_data ^1.3.0
- desktop_webview_auth 0.0.15
  - crypto ^3.0.3
  - flutter any
  - http ^1.0.0
  - flutter_web_plugins any
  - plugin_platform_interface ^2.1.4
- email_validator 2.1.17
- fake_async 1.3.1
  - clock ^1.1.0
  - collection ^1.15.0
- firebase_auth_platform_interface 7.1.9
  - _flutterfire_internals ^1.3.26
  - collection ^1.16.0
  - firebase_core ^2.27.1
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_auth_web 5.10.0
  - firebase_auth_platform_interface ^7.1.9
  - firebase_core ^2.27.1
  - firebase_core_web ^2.12.0
  - flutter any
  - flutter_web_plugins any
  - http_parser ^4.0.0
  - js ^0.6.3
  - meta ^1.8.0
  - web ^0.5.1
- firebase_core_platform_interface 5.0.0
  - collection ^1.0.0
  - flutter any
  - flutter_test any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_core_web 2.12.0
  - firebase_core_platform_interface ^5.0.0
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
  - meta ^1.8.0
  - web ^0.5.1
- firebase_database_platform_interface 0.2.5+26
  - _flutterfire_internals ^1.3.26
  - collection ^1.14.3
  - firebase_core ^2.27.1
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_database_web 0.2.3+26
  - firebase_core ^2.27.1
  - firebase_core_web ^2.12.0
  - firebase_database_platform_interface ^0.2.5+26
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
- firebase_dynamic_links 5.4.18
  - firebase_core ^2.27.1
  - firebase_core_platform_interface ^5.0.0
  - firebase_dynamic_links_platform_interface ^0.2.6+26
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_dynamic_links_platform_interface 0.2.6+26
  - _flutterfire_internals ^1.3.26
  - firebase_core ^2.27.1
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_storage_platform_interface 5.1.13
  - _flutterfire_internals ^1.3.26
  - collection ^1.15.0
  - firebase_core ^2.27.1
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_storage_web 3.8.0
  - _flutterfire_internals ^1.3.26
  - async ^2.5.0
  - firebase_core ^2.27.1
  - firebase_core_web ^2.12.0
  - firebase_storage_platform_interface ^5.1.13
  - flutter any
  - flutter_web_plugins any
  - http >=0.13.0 <2.0.0
  - js ^0.6.3
  - meta ^1.8.0
  - web ^0.5.1
- firebase_ui_localizations 1.10.2
  - flutter any
  - flutter_localizations any
  - path ^1.8.3
- firebase_ui_oauth 1.5.1
  - desktop_webview_auth ^0.0.14
  - firebase_auth ^4.17.5
  - firebase_ui_auth ^1.13.1
  - firebase_ui_shared ^1.4.1
  - flutter_svg ^2.0.9
  - flutter any
- firebase_ui_shared 1.4.1
  - flutter any
- fixnum 1.1.0
- flutter_localizations 0.0.0
  - flutter any
  - intl 0.18.1
  - characters 1.3.0
  - clock 1.1.1
  - collection 1.18.0
  - material_color_utilities 0.8.0
  - meta 1.11.0
  - path 1.9.0
  - vector_math 2.1.4
- flutter_svg 2.0.10+1
  - flutter any
  - http ^1.0.0
  - vector_graphics ^1.1.11
  - vector_graphics_codec ^1.1.11
  - vector_graphics_compiler ^1.1.11
- flutter_web_plugins 0.0.0
  - flutter any
  - characters 1.3.0
  - collection 1.18.0
  - material_color_utilities 0.8.0
  - meta 1.11.0
  - vector_math 2.1.4
- google_identity_services_web 0.3.1+1
  - meta ^1.3.0
  - web ^0.5.1
- google_sign_in_android 6.1.21
  - flutter any
  - google_sign_in_platform_interface ^2.2.0
- google_sign_in_ios 5.7.4
  - flutter any
  - google_sign_in_platform_interface ^2.2.0
- google_sign_in_platform_interface 2.4.5
  - flutter any
  - plugin_platform_interface ^2.1.7
- google_sign_in_web 0.12.4
  - flutter any
  - flutter_web_plugins any
  - google_identity_services_web ^0.3.1
  - google_sign_in_platform_interface ^2.4.0
  - http >=0.13.0 <2.0.0
  - web ^0.5.0
- http_parser 4.0.2
  - collection ^1.15.0
  - source_span ^1.8.0
  - string_scanner ^1.1.0
  - typed_data ^1.3.0
- intl 0.18.1
  - clock ^1.1.0
  - meta ^1.0.2
  - path ^1.8.0
- js 0.6.7
  - meta ^1.7.0
- leak_tracker 10.0.0
  - clock ^1.1.1
  - collection ^1.15.0
  - meta ^1.8.0
  - path ^1.8.3
  - vm_service >=11.10.0 <15.0.0
- leak_tracker_flutter_testing 2.0.1
  - flutter any
  - leak_tracker >=10.0.0 <11.0.0
  - leak_tracker_testing >=2.0.1 <3.0.0
  - matcher ^0.12.16
  - meta ^1.8.0
- leak_tracker_testing 2.0.1
  - leak_tracker >=9.0.0 <11.0.0
  - matcher ^0.12.16
  - meta ^1.11.0
- lints 3.0.0
- matcher 0.12.16+1
  - async ^2.10.0
  - meta ^1.8.0
  - stack_trace ^1.10.0
  - term_glyph ^1.2.0
  - test_api >=0.5.0 <0.8.0
- material_color_utilities 0.8.0
  - collection ^1.15.0
- meta 1.11.0
- path 1.9.0
- path_parsing 1.0.1
  - vector_math ^2.1.0
  - meta ^1.3.0
- petitparser 6.0.2
  - meta ^1.9.0
- plugin_platform_interface 2.1.8
  - meta ^1.3.0
- sky_engine 0.0.99
- source_span 1.10.0
  - collection ^1.15.0
  - path ^1.8.0
  - term_glyph ^1.2.0
- sprintf 7.0.0
- stack_trace 1.11.1
  - path ^1.8.0
- stream_channel 2.1.2
  - async ^2.5.0
- string_scanner 1.2.0
  - source_span ^1.8.0
- term_glyph 1.2.1
- test_api 0.6.1
  - async ^2.5.0
  - boolean_selector ^2.1.0
  - collection ^1.15.0
  - meta ^1.3.0
  - source_span ^1.8.0
  - stack_trace ^1.10.0
  - stream_channel ^2.1.0
  - string_scanner ^1.1.0
  - term_glyph ^1.2.0
- typed_data 1.3.2
  - collection ^1.15.0
- vector_graphics 1.1.11+1
  - flutter any
  - http ^1.0.0
  - vector_graphics_codec 1.1.11+1
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1
  - args ^2.3.0
  - meta ^1.7.0
  - path_parsing ^1.0.1
  - xml ^6.3.0
  - vector_graphics_codec 1.1.11+1
  - path ^1.8.0
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.5.1
- xml 6.5.0
  - collection ^1.18.0
  - meta ^1.9.0
  - petitparser ^6.0.0
</pre>
</details>

### Steps to reproduce

- Follow normal auth procedure
- `FirebaseAuth.instance.currentUser` only has an idToken, but does not have the accessToken returned from `signInWithIdp` (viewable from network inspector)

### Expected Behavior

There should be access to the `accessToken` so I can make api calls to a GCP backend.

### Actual Behavior

The info is available in the network tab, but not exposed anywhere in the API (afaict), so I have to make some separate call to GoogleSignIn

**Comment by russellwheatley** [comment]
Hey @bedardjo - could you show me a code implementation of what you expect? I don't quite follow what you mean by no accessToken on `FirebaseAuth.instance.currentUser`.
