### ISSUE TITLE
Incompatible with firebase_auth: ^5.0.0

### ISSUE THREAD

**Issue by thiagofmedeiros** [firebase/FirebaseUI-Flutter#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Auth

### What platform(s) does this bug affect?

Web

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
 Because firebase_ui_oauth_google 1.3.2 depends on firebase_auth ^4.17.5 and no versions of firebase_ui_oauth_google match >1.3.2 <2.0.0,
  firebase_ui_oauth_google ^1.3.2 requires firebase_auth ^4.17.5.
So, because baintec_page depends on both firebase_auth ^5.0.0 and firebase_ui_oauth_google ^1.3.2, version solving failed.

</pre>
</details>

### Steps to reproduce

Try to update to firebase new libraries

### Expected Behavior

compatibility

### Actual Behavior

incompatibility

**Comment by larssn** [comment]
@lesnitsky Can we get some eyes on this?

`firebase_ui_firestore` is currently holding back all major firebase plugins (cloud_firestore etc).

Thanks

**Comment by mulderpf** [comment]
We reported it here last week and it was closed as fixed: https://github.com/firebase/FirebaseUI-Flutter/issues/355 - I just tried, after giving it 5 days and the new version is still not available.  It's all good to have checked in code, but it's not really helpful if we cannot get it.

**Comment by russellwheatley** [comment]
I cutting a new release, will let you know when it is done 🙏

**Comment by russellwheatley** [comment]
Latest release is out now 👍
