### ISSUE TITLE
South Sudan Missing on countries.dart file

### ISSUE THREAD

**Issue by ILBPBillMari** [firebase/FirebaseUI-Flutter#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Auth

### What platform(s) does this bug affect?

Android, iOS

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
  
</pre>
</details>

### Steps to reproduce

view countries.dart file https://github.com/firebase/FirebaseUI-Flutter/blob/main/packages/firebase_ui_auth/lib/src/configs/countries.dart

### Expected Behavior

Find South Sudanas one of the countries listed

### Actual Behavior

South Sudan is missing in the countries needed

**Comment by russellwheatley** [comment]
Hey @ILBPBillMari - if you wish to create a PR with the translations for South Sudan, I'd help shepherd it through.

Here is an example of a PR for creating the labels: https://github.com/firebase/FirebaseUI-Flutter/pull/332/files

follow this guide to generate the labels: https://github.com/firebase/FirebaseUI-Flutter/blob/main/packages/firebase_ui_localizations/README.md
