### ISSUE TITLE
FirestoreDataTable Page Not Resetting

### ISSUE THREAD

**Issue by Mahender-Kumar** [firebase/FirebaseUI-Flutter#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Firestore

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
  
</pre>
</details>

### Steps to reproduce

```dart
class MyWidget extends ConsumerWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context, ref) {
    final usersQuery = FirebaseFirestore.instance
        .collection(
            'users/${userId}/calls')
        .orderBy('timestamp', descending: true);
    return ListView(
      children: [
        FirestoreDataTable(
          rowsPerPage: 20,
          dataRowMaxHeight: 40,
          dataRowMinHeight: 24,
          headingRowHeight: 40.0,
          columnSpacing: 24.0,
          showCheckboxColumn: false,
          query: usersQuery,
          showFirstLastButtons: true,
          columnLabels: {
            'timestamp': const Text('Added On'),
          },
        ),
      ],
    );
  }
}

```

### Expected Behavior

if the query is changing the page should reset i.e. _rowindex should be set to 0

### Actual Behavior

if the query is changing the page is not reseting i.e. _firstRowIndex is not  setting to 0

**Comment by Mahender-Kumar** [comment]
@override
  void didUpdateWidget(PaginatedTable oldWidget) {
    super.didUpdateWidget(oldWidget);

    if (oldWidget.queryCHanged != widget.queryCHanged) {
      // print('quwey changed');
      oldWidget.source.removeListener(_handleDataSourceChanged);
      widget.source.addListener(_handleDataSourceChanged);
      _updateCaches();
      pageTo(0);
    }
    if (oldWidget.source != widget.source) {
      // print('source changed');
      oldWidget.source.removeListener(_handleDataSourceChanged);
      widget.source.addListener(_handleDataSourceChanged);
      _updateCaches();
    }
  }

**Comment by russellwheatley** [comment]
Hi @Mahender-Kumar - could you provide more information on what the issue is? It might help if you provide a full reproducible code repo and steps for how to reproduce as I'm not sure what the bug is.
