### ISSUE TITLE
🐛 [firebase_ui_auth 1.1.10] strange behaviour with "enable more sign in methods"

### ISSUE THREAD

**Issue by graemep-nz** [firebase/FirebaseUI-Flutter#39]
## Bug report
When there is only one auth provider configured, a problem occurs with sign-in methods button and enable more sign-in methods.

See  https://github.com/firebase/flutterfire/issues/10431 for files etc.
Issue number 2 in firebase_ui_auth 1.1.10 issues.pdf

see also
https://github.com/firebase/flutterfire/issues/10431
https://github.com/firebase/flutterfire/issues/10433
https://github.com/firebase/flutterfire/issues/10434
https://github.com/firebase/FirebaseUI-Flutter/issues/36
https://github.com/firebase/FirebaseUI-Flutter/issues/35

**Comment by lesnitsky** [comment]
as of `Flutter 3.13.1 • channel stable` and `firebase_ui_auth: 1.7.0` this is no longer reproducible (icons are not clickable in "Sign in methods" row on `ProfileScreen`)
