### ISSUE TITLE
🐛 [firebase_ui_firestore, firebase_ui_database] Pagination widgets do not use platform adaptive loading indicators

### ISSUE THREAD

**Issue by OutdatedGuy** [firebase/FirebaseUI-Flutter#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Database, Firebase UI Firestore

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
  
</pre>
</details>

### Steps to reproduce

Use default Example of `firebase_ui_firestore` and `firebase_ui_database` for pagination and see that loading widget is not `CupertinoActivityIndicator` on iOS and macOS platforms by default.

### Expected Behavior

Loading widget should be `CupertinoActivityIndicator` on apple platforms.

### Actual Behavior

Loading widget is a Material Loading Indicator

**Comment by russellwheatley** [comment]
@OutdatedGuy - thanks for the catch! This does sound like an issue. Do you think you could open a PR and I can take a look? Otherwise, I can eventually get round to investigating but might be a bit slower than yourself 😄

**Comment by OutdatedGuy** [comment]
Hi @russellwheatley, I have already created a PR and linked it to this issue. Please look into  https://github.com/firebase/FirebaseUI-Flutter/pull/399

**Comment by russellwheatley** [comment]
ah, thanks, I've taken a look and it LGTM 👍
