### ISSUE TITLE
🐛 [flutterfire_ui] Missing localization in profile_screen

### ISSUE THREAD

**Issue by przemek-lagan** [firebase/FirebaseUI-Flutter#54]
## Bug report

There are six hardcoded messages in english in profile_screen, concerning verification e-mail.
It is impossible to override them when making localization, that is not supported yet.

### Steps to reproduce

Go to ProfileScreen with unverified account and locale other than English.
Look in profile_screen.dart for 'Email is not verified' strings etc.

### Expected behavior

Strings should be replaced with labels (l.variablename).

### Sample project

I've corrected the strings in my fork of flutterfire, but my solution lacks translations for supported languages.
Also, that could be a breaking change, as the labels are required, depending of localization method used.

**Comment by SCarcalicea** [comment]
Any news about this happening any time soon?
