### ISSUE TITLE
sendEmailVerification requires FDL (deprecated) domain.

### ISSUE THREAD

**Issue by kelnishi** [firebase/FirebaseUI-Flutter#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found no duplicates.

### What plugin is this bug for?

Firebase UI Auth

### What platform(s) does this bug affect?

Web

### List of dependencies used.

<details>
<summary>flutter pub deps -s list</summary>
<pre>
Dart SDK 3.1.0
Flutter SDK 3.13.0
saru 1.0.0+1

dependencies:
- flutter 0.0.0
  - characters 1.3.0
  - collection 1.17.2
  - material_color_utilities 0.5.0
  - meta 1.9.1
  - vector_math 2.1.4
  - web 0.1.4-beta
  - sky_engine any
- flutter_bloc 8.1.3
  - bloc ^8.1.1
  - flutter any
  - provider ^6.0.0
- bloc 8.1.2
  - meta ^1.3.0
- firebase_core 2.15.1
  - firebase_core_platform_interface ^4.8.0
  - firebase_core_web ^2.7.0
  - flutter any
  - meta ^1.8.0
- firebase_auth 4.8.0
  - firebase_auth_platform_interface ^6.17.0
  - firebase_auth_web ^5.7.0
  - firebase_core ^2.15.1
  - firebase_core_platform_interface ^4.8.0
  - flutter any
  - meta ^1.8.0
- firebase_ui_auth 1.6.4
  - email_validator ^2.0.1
  - firebase_auth ^4.7.2
  - firebase_core ^2.15.0
  - firebase_dynamic_links ^5.3.4
  - firebase_ui_localizations ^1.5.2
  - firebase_ui_oauth ^1.4.8
  - firebase_ui_shared ^1.3.1
  - flutter any
  - flutter_localizations any
- google_sign_in 6.1.4
  - flutter any
  - google_sign_in_android ^6.1.0
  - google_sign_in_ios ^5.5.0
  - google_sign_in_platform_interface ^2.4.0
  - google_sign_in_web ^0.12.0
- cupertino_icons 1.0.5
- firebase_ui_oauth_apple 1.2.8
  - firebase_auth ^4.7.3
  - firebase_ui_oauth ^1.4.8
  - flutter any
- firebase_ui_oauth_facebook 1.2.8
  - firebase_auth ^4.7.3
  - firebase_ui_oauth ^1.4.8
  - flutter any
  - flutter_facebook_auth ^5.0.8
- firebase_ui_oauth_google 1.2.8
  - firebase_auth ^4.7.3
  - firebase_ui_oauth ^1.4.8
  - flutter any
  - google_sign_in ^6.1.0
- firebase_ui_oauth_twitter 1.2.8
  - flutter any
  - firebase_auth ^4.7.3
  - firebase_ui_oauth ^1.4.8
  - twitter_login ^4.3.2

dev dependencies:
- flutter_test 0.0.0
  - flutter any
  - test_api 0.6.0
  - matcher 0.12.16
  - path 1.8.3
  - fake_async 1.3.1
  - clock 1.1.1
  - stack_trace 1.11.0
  - vector_math 2.1.4
  - async 2.11.0
  - boolean_selector 2.1.1
  - characters 1.3.0
  - collection 1.17.2
  - material_color_utilities 0.5.0
  - meta 1.9.1
  - source_span 1.10.0
  - stream_channel 2.1.1
  - string_scanner 1.2.0
  - term_glyph 1.2.1
  - web 0.1.4-beta
- flutter_lints 2.0.2
  - lints ^2.0.0

transitive dependencies:
- _flutterfire_internals 1.3.5
  - collection ^1.0.0
  - firebase_core ^2.15.1
  - firebase_core_platform_interface ^4.8.0
  - flutter any
  - meta ^1.8.0
- args 2.4.2
- async 2.11.0
  - collection ^1.15.0
  - meta ^1.1.7
- boolean_selector 2.1.1
  - source_span ^1.8.0
  - string_scanner ^1.1.0
- characters 1.3.0
- clock 1.1.1
- collection 1.17.2
- crypto 3.0.3
  - typed_data ^1.3.0
- desktop_webview_auth 0.0.12
  - crypto ^3.0.1
  - flutter any
  - http ^0.13.3
  - flutter_web_plugins any
  - plugin_platform_interface ^2.1.3
- email_validator 2.1.17
- facebook_auth_desktop 0.0.9
  - flutter any
  - http ^0.13.5
  - flutter_secure_storage ^8.0.0
  - flutter_facebook_auth_platform_interface ^4.1.1
- fake_async 1.3.1
  - clock ^1.1.0
  - collection ^1.15.0
- firebase_auth_platform_interface 6.17.0
  - _flutterfire_internals ^1.3.5
  - collection ^1.16.0
  - firebase_core ^2.15.1
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_auth_web 5.7.0
  - firebase_auth_platform_interface ^6.17.0
  - firebase_core ^2.15.1
  - firebase_core_web ^2.7.0
  - flutter any
  - flutter_web_plugins any
  - http_parser ^4.0.0
  - js ^0.6.3
  - meta ^1.8.0
- firebase_core_platform_interface 4.8.0
  - collection ^1.0.0
  - flutter any
  - flutter_test any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_core_web 2.7.0
  - firebase_core_platform_interface ^4.8.0
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
  - meta ^1.8.0
- firebase_dynamic_links 5.3.5
  - firebase_core ^2.15.1
  - firebase_core_platform_interface ^4.8.0
  - firebase_dynamic_links_platform_interface ^0.2.6+5
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_dynamic_links_platform_interface 0.2.6+5
  - _flutterfire_internals ^1.3.5
  - firebase_core ^2.15.1
  - flutter any
  - meta ^1.8.0
  - plugin_platform_interface ^2.1.3
- firebase_ui_localizations 1.5.2
  - flutter any
  - flutter_localizations any
  - path ^1.8.2
- firebase_ui_oauth 1.4.8
  - desktop_webview_auth ^0.0.11
  - firebase_auth ^4.7.3
  - firebase_ui_auth ^1.6.3
  - firebase_ui_shared ^1.3.0
  - flutter_svg ^2.0.5
  - flutter any
- firebase_ui_shared 1.3.1
  - flutter any
- flutter_facebook_auth 5.0.11
  - flutter any
  - flutter_facebook_auth_platform_interface ^4.1.1
  - flutter_facebook_auth_web ^4.1.1
  - facebook_auth_desktop ^0.0.9
- flutter_facebook_auth_platform_interface 4.1.1
  - flutter any
  - plugin_platform_interface ^2.1.2
- flutter_facebook_auth_web 4.1.1
  - flutter any
  - flutter_web_plugins any
  - js ^0.6.3
  - flutter_facebook_auth_platform_interface ^4.1.1
- flutter_localizations 0.0.0
  - flutter any
  - intl 0.18.1
  - characters 1.3.0
  - clock 1.1.1
  - collection 1.17.2
  - material_color_utilities 0.5.0
  - meta 1.9.1
  - path 1.8.3
  - vector_math 2.1.4
  - web 0.1.4-beta
- flutter_secure_storage 8.0.0
  - flutter any
  - flutter_secure_storage_linux ^1.1.3
  - flutter_secure_storage_macos ^3.0.0
  - flutter_secure_storage_platform_interface ^1.0.1
  - flutter_secure_storage_web ^1.1.1
  - flutter_secure_storage_windows ^2.0.0
  - meta ^1.3.0
- flutter_secure_storage_linux 1.1.3
  - flutter any
  - flutter_secure_storage_platform_interface ^1.0.1
- flutter_secure_storage_macos 3.0.0
  - flutter any
  - flutter_secure_storage_platform_interface ^1.0.1
- flutter_secure_storage_platform_interface 1.0.1
  - flutter any
  - plugin_platform_interface ^2.0.1
- flutter_secure_storage_web 1.1.1
  - flutter any
  - flutter_secure_storage_platform_interface ^1.0.1
  - flutter_web_plugins any
  - js ^0.6.3
- flutter_secure_storage_windows 2.0.0
  - flutter any
  - flutter_secure_storage_platform_interface ^1.0.1
- flutter_svg 2.0.7
  - flutter any
  - vector_graphics ^1.1.7
  - vector_graphics_codec ^1.1.7
  - vector_graphics_compiler ^1.1.7
- flutter_web_plugins 0.0.0
  - flutter any
  - characters 1.3.0
  - collection 1.17.2
  - material_color_utilities 0.5.0
  - meta 1.9.1
  - vector_math 2.1.4
  - web 0.1.4-beta
- google_identity_services_web 0.2.1
  - js ^0.6.4
  - meta ^1.3.0
- google_sign_in_android 6.1.18
  - flutter any
  - google_sign_in_platform_interface ^2.2.0
- google_sign_in_ios 5.6.2
  - flutter any
  - google_sign_in_platform_interface ^2.2.0
- google_sign_in_platform_interface 2.4.1
  - flutter any
  - plugin_platform_interface ^2.1.0
  - quiver ^3.0.0
- google_sign_in_web 0.12.0+3
  - flutter any
  - flutter_web_plugins any
  - google_identity_services_web ^0.2.1
  - google_sign_in_platform_interface ^2.4.0
  - http >=0.13.0 <2.0.0
  - js ^0.6.3
- http 0.13.6
  - async ^2.5.0
  - http_parser ^4.0.0
  - meta ^1.3.0
- http_parser 4.0.2
  - collection ^1.15.0
  - source_span ^1.8.0
  - string_scanner ^1.1.0
  - typed_data ^1.3.0
- intl 0.18.1
  - clock ^1.1.0
  - meta ^1.0.2
  - path ^1.8.0
- js 0.6.7
  - meta ^1.7.0
- lints 2.1.1
- matcher 0.12.16
  - async ^2.10.0
  - meta ^1.8.0
  - stack_trace ^1.10.0
  - term_glyph ^1.2.0
  - test_api >=0.5.0 <0.7.0
- material_color_utilities 0.5.0
  - collection ^1.15.0
- meta 1.9.1
- nested 1.0.0
  - flutter any
- path 1.8.3
- path_parsing 1.0.1
  - vector_math ^2.1.0
  - meta ^1.3.0
- petitparser 5.4.0
  - meta ^1.9.0
- plugin_platform_interface 2.1.5
  - meta ^1.3.0
- provider 6.0.5
  - collection ^1.15.0
  - flutter any
  - nested ^1.0.0
- quiver 3.2.1
  - matcher ^0.12.10
- sky_engine 0.0.99
- source_span 1.10.0
  - collection ^1.15.0
  - path ^1.8.0
  - term_glyph ^1.2.0
- stack_trace 1.11.0
  - path ^1.8.0
- stream_channel 2.1.1
  - async ^2.5.0
- string_scanner 1.2.0
  - source_span ^1.8.0
- term_glyph 1.2.1
- test_api 0.6.0
  - async ^2.5.0
  - boolean_selector ^2.1.0
  - collection ^1.15.0
  - meta ^1.3.0
  - source_span ^1.8.0
  - stack_trace ^1.10.0
  - stream_channel ^2.1.0
  - string_scanner ^1.1.0
  - term_glyph ^1.2.0
- twitter_login 4.4.0
  - crypto ^3.0.1
  - flutter any
  - http ^0.13.3
- typed_data 1.3.2
  - collection ^1.15.0
- vector_graphics 1.1.7
  - flutter any
  - vector_graphics_codec 1.1.7
- vector_graphics_codec 1.1.7
- vector_graphics_compiler 1.1.7
  - args ^2.3.0
  - meta ^1.7.0
  - path_parsing ^1.0.1
  - xml ^6.3.0
  - vector_graphics_codec 1.1.7
- vector_math 2.1.4
- web 0.1.4-beta
- xml 6.3.0
  - collection ^1.17.0
  - meta ^1.9.0
  - petitparser ^5.4.0
</pre>
</details>

### Steps to reproduce

Using the packages/firebase_ui_auth/example/lib/main.dart example. 
1. Click Register for a new email account
2. Enter email and passwords
3. Click Register to continue to email verification.
4. Error gets thrown here if No FDL is configured in Firebase Console.

### Expected Behavior

FDL is deprecated and EOL in 2025. Dynamic links should not be used by default in emails. Dynamic links should not be required for sending emails. Would be nice if it just used the non-dynamic link root URL for %LINK%s.

### Actual Behavior

Having no FDL domain crashes the account creation/password reset/email login flow.

**Comment by lesnitsky** [comment]
Closing in favour of #7
