### ISSUE TITLE
Add option to collect user name during email registration

### ISSUE THREAD

**Issue by lesnitsky** [firebase/FirebaseUI-Flutter#76]
### Discussed in https://github.com/firebase/FirebaseUI-Flutter/discussions/69

<div type='discussions-op-text'>

<sup>Originally posted by **bakua** August 23, 2023</sup>
Hi there! I've been enjoying Firebase UI Auth, but I've noticed something. While social logins easily get display names, email sign-ups don't. Would it be possible to add an option to collect user names during email registration? It would really help keep a consistent experience for users. Thank you so much for considering this!</div>

**Comment by lesnitsky** [comment]
As mentioned in discussion comments, this was picked up by @YassinNouh21

**Comment by lesnitsky** [comment]
@YassinNouh21 are you willing/have time to address my [comment](https://github.com/firebase/FirebaseUI-Flutter/pull/82#issuecomment-1700958112)?

**Comment by YassinNouh21** [comment]
@lesnitsky  yeah sorry for being late I will work on it these days

**Comment by YassinNouh21** [comment]
@lesnitsky  I just pushed new commits in my PR
